# Imports

In [3]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import datetime
import logging
import os

import pandas as pd
# /venv/lib/python3.12/site-packages/gspread_pandas/spread.py:401: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)` .replace("", np.nan)
pd.set_option('future.no_silent_downcasting', True)

import helpers.hdbg as hdbg
import helpers.henv as henv
import helpers.hpandas as hpandas
import helpers.hprint as hprint
import helpers.hcache as hcache

#hcache.get_global_cache_info()
#hcache.clear_global_cache("all")

import config_root.config as cconfig

# %%
hdbg.init_logger(verbosity=logging.INFO)

_LOG = logging.getLogger(__name__)

_LOG.info("%s", henv.get_system_signature()[0])

hprint.config_notebook()

WARNING: Running in Jupyter
INFO  > cmd='/venv/lib/python3.12/site-packages/ipykernel_launcher.py -f /home/.local/share/jupyter/runtime/kernel-6c5194bf-acdb-4656-a6d6-4694afd43157.json'
INFO  # Git
  branch_name='CmampTask11020_Compute_yamm_stats'
  hash='ffe7bbbc4'
  # Last commits:
    * ffe7bbbc4 GP Saggese Update                                                            (  18 hours ago) Wed Feb 12 23:16:09 2025  (HEAD -> CmampTask11020_Compute_yamm_stats, origin/CmampTask11020_Compute_yamm_stats)
    * b975b2266 GP Saggese Update                                                            (  18 hours ago) Wed Feb 12 22:46:55 2025
    * 62263d730 GP Saggese Update                                                            (    2 days ago) Tue Feb 11 21:59:17 2025
# Machine info
  system=Linux
  node name=9b21dea71c71
  release=6.10.14-linuxkit
  version=#1 SMP Fri Nov 29 17:22:03 UTC 2024
  machine=aarch64
  processor=aarch64
  cpu count=8
  cpu freq=None
  memory=svmem(total=8218251264, available=5096345600, percent=38.0, used=2903441408, free=394235904, active=2215108608, inactive=4227948544, buffers=1160503296, cached=3760070656, shared=10620928, slab=1216155648)
  disk usage=sdiskusage(total=62671097856, used=40417628160, free=19036753920, percent=68.0)
# Packages
  python: 3.12.3
  cvxopt: 1.3.2
  cvxpy: 1.5.3
  gluonnlp: ?
  gluonts: ?
  joblib: 1.4.2
  mxnet: ?
  numpy: 2.1.3
  pandas: 2.2.3
  pyarrow: 18.0.0
  scipy: 1.14.1
  seaborn: 0.13.2
  sklearn: 1.5.2
  statsmodels: 0.14.4

In [37]:
!pwd

/app/ck_marketing/signal_nfx

In [6]:
file_name = "/app/ck_marketing/linkedin/industry_codes_v2.csv"
df = pd.read_csv(file_name)
df.set_index("id", inplace=True)
df.head(3)

#df["label"].to_dict()

                               label                                          hierarchy                                        description
id
1    Defense and Space Manufacturing  Manufacturing > Transportation Equipment Manuf...  This industry includes entities that manufactu...
10                    Legal Services             Professional Services > Legal Services  This industry includes entities that offer leg...
100         Non-profit Organizations       Consumer Services > Non-profit Organizations  This industry includes entities that provide p...

In [7]:
df

                                                  label                                          hierarchy                                        description
id
1                       Defense and Space Manufacturing  Manufacturing > Transportation Equipment Manuf...  This industry includes entities that manufactu...
10                                       Legal Services             Professional Services > Legal Services  This industry includes entities that offer leg...
100                            Non-profit Organizations       Consumer Services > Non-profit Organizations  This industry includes entities that provide p...
1005                  Household Appliance Manufacturing  Manufacturing > Appliances, Electrical, and El...  This industry includes entities that manufactu...
101                                         Fundraising  Administrative and Support Services > Fundraising  This industry includes entities that provide b...
102                       Strategic Management Services  Professional Services > Business Consulting an...  This industry includes entities that advise on...
1029             Transportation Equipment Manufacturing  Manufacturing > Transportation Equipment Manuf...  This industry includes entities that manufactu...
103                                 Writing and Editing  Administrative and Support Services > Writing ...  This industry includes entities that create do...
104                             Staffing and Recruiting  Administrative and Support Services > Staffing...  This industry includes entities that: 1. List ...
1042                  Motor Vehicle Parts Manufacturing  Manufacturing > Transportation Equipment Manuf...  This industry includes entities that manufactu...
105                  Professional Training and Coaching     Education > Professional Training and Coaching  This industry includes entities that offer tra...
106       Venture Capital and Private Equity Principals  Financial Services > Capital Markets > Venture...  This industry includes entities that act as pr...
107                             Political Organizations  Consumer Services > Civic and Social Organizat...  This industry includes entities that promote t...
108                        Translation and Localization  Administrative and Support Services > Translat...  This industry includes entities that translate...
1080  Household and Institutional Furniture Manufact...  Manufacturing > Furniture and Home Furnishings...  This industry includes entities that manufactu...
109                                      Computer Games  Technology, Information and Media > Technology...  This industry includes entities that produce u...
1090        Office Furniture and Fixtures Manufacturing  Manufacturing > Furniture and Home Furnishings...  This industry includes entities that manufactu...
1095                  Mattress and Blinds Manufacturing  Manufacturing > Furniture and Home Furnishings...  This industry includes entities that manufactu...
11                     Business Consulting and Services  Professional Services > Business Consulting an...  This industry includes entities that provide a...
110                                     Events Services  Administrative and Support Services > Events S...  This industry includes entities that organize,...
111                                 Retail Art Supplies                       Retail > Retail Art Supplies  This industry includes entities that retail ar...
112   Appliances, Electrical, and Electronics Manufa...  Manufacturing > Appliances, Electrical, and El...  This industry includes entities that manufactu...
1128                 Wholesale Motor Vehicles and Parts     Wholesale > Wholesale Motor Vehicles and Parts  This industry includes entities that distribut...
113                        Online Audio and Video Media  Technology, Information and Media > Technology...  This industry includes entities that publish a...
1137           Wholesale Furniture and Home Furnishings  Wholesale > Wholesale Furniture and Home Furni...  This industry includes entities that distribut...
114                             Nanotechnology Research  Professional Services > Research Services > Na...  This industry includes entities that conduct n...
115                                           Musicians                Entertainment Providers > Musicians  This industry includes 1. Groups that produce ...
1153       Wholesale Photography Equipment and Supplies  Wholesale > Wholesale Photography Equipment an...  This industry includes entities that distribut...
1157                       Wholesale Computer Equipment           Wholesale > Wholesale Computer Equipment  This industry includes entities that distribut...
116   Transportation, Logistics, Supply Chain and St...  Transportation, Logistics, Supply Chain and St...  This industry includes entities that store and...
1166                      Wholesale Metals and Minerals          Wholesale > Wholesale Metals and Minerals  This industry includes entities that engage in...
117                              Plastics Manufacturing  Manufacturing > Plastics and Rubber Product Ma...  This industry includes entities that process n...
1171  Wholesale Appliances, Electrical, and Electronics  Wholesale > Wholesale Appliances, Electrical, ...  This industry includes entities that distribut...
1178    Wholesale Hardware, Plumbing, Heating Equipment  Wholesale > Wholesale Hardware, Plumbing, Heat...  This industry includes entities that distribut...
118                       Computer and Network Security  Professional Services > IT Services and IT Con...  This industry includes entities that provide s...
1187                                Wholesale Machinery                    Wholesale > Wholesale Machinery  This industry includes entities that distribut...
119                                   Wireless Services  Technology, Information and Media > Media and ...  This industry includes entities that operate a...
12                               Biotechnology Research  Professional Services > Research Services > Bi...  This industry includes entities that conduct b...
120                      Alternative Dispute Resolution  Professional Services > Legal Services > Alter...  This industry includes entities (except office...
1206                     Wholesale Recyclable Materials         Wholesale > Wholesale Recyclable Materials  This industry includes entities that distribut...
1208                 Wholesale Luxury Goods and Jewelry     Wholesale > Wholesale Luxury Goods and Jewelry  This industry includes entities that distribut...
121                         Security and Investigations  Administrative and Support Services > Security...  This industry includes entities that: 1. Provi...
1212                           Wholesale Paper Products               Wholesale > Wholesale Paper Products  This industry includes entities that distribut...
122                                 Facilities Services  Administrative and Support Services > Faciliti...  This industry includes entities that provide o...
1221                       Wholesale Drugs and Sundries           Wholesale > Wholesale Drugs and Sundries  This industry includes entities that distribut...
1222              Wholesale Apparel and Sewing Supplies  Wholesale > Wholesale Apparel and Sewing Supplies  This industry includes entities that distribut...
123               Outsourcing and Offshoring Consulting  Professional Services > Business Consulting an...  This industry includes entities that provide o...
1230                                 Wholesale Footwear                     Wholesale > Wholesale Footwear  This industry includes entities that distribut...
1231                        Wholesale Food and Beverage            Wholesale > Wholesale Food and Beverage  This industry includes entities that distribut...
124                       Wellness and Fitness Services  Entertainment Providers > Recreational Facilit...  This industry includes entities that: 1. Opera...
125                                Alternative Medicine  Hospitals and Health Care > Medical Practices ...  This industry includes independent health prac...
1250                        Wholesale Raw Farm Products            Wholesale > Wholesale Raw Farm Products  This industry includes entities that distribut...
1257             Wholesale Chemical and Allied Products  Wholesale > Wholesale Chemical and Allied Prod...  This industry includes entities that distribut...
126                                    Media Production  Technology, Information and Media > Media and ...  This industry includes entities that produce m...
1262         Wholesale Petroleum and Petroleum Products  Wholesale > Wholesale Petroleum and Petroleum ...  This industry includes entities that distribut...
1267                      Wholesale Alcoholic Beverages          Wholesale > Wholesale Alcoholic Beverages  This industry includes entities that distribut...
127                       Animation and Post-production  Technology, Information and Media > Media and ...  This industry includes entities that provide s...
128                 Leasing Non-residential Real Estate  Real Estate and Equipment Rental Services > Re...  This industry includes entities that act as le...
1285                     Internet Marketplace Platforms  Technology, Information and Media > Technology...  This industry includes entities that provide a...
129                                     Capital Markets               Financial Services > Capital Markets  This industry includes entities that: 1. Under...
1292                              Retail Motor Vehicles                     Retail > Retail Motor Vehicles  This industry includes entities that primarily...
13                                    Medical Practices      Hospitals and Health Care > Medical Practices  This industry includes individual medical prac...
130                                         Think Tanks  Professional Services > Research Services > Th...  This industry includes entities that conduct r...
1309              Retail Furniture and Home Furnishings     Retail > Retail Furniture and Home Furnishings  This industry includes entities that primarily...
131                  Philanthropic Fundraising Services  Consumer Services > Philanthropic Fundraising ...  This industry includes grantmaking foundations...
1319  Retail Appliances, Electrical, and Electronic ...  Retail > Retail Appliances, Electrical, and El...  This industry includes entities that primarily...
132                                E-Learning Providers                   Education > E-Learning Providers  This industry includes entities that offer ins...
1324     Retail Building Materials and Garden Equipment  Retail > Retail Building Materials and Garden ...  This industry includes entities that primarily...
133                                           Wholesale                                          Wholesale  This industry includes entities that distribut...
1339                           Food and Beverage Retail                  Retail > Food and Beverage Retail  This industry includes entities that primarily...
134                         Wholesale Import and Export            Wholesale > Wholesale Import and Export  This industry includes entities that facilitat...
135                  Industrial Machinery Manufacturing  Manufacturing > Machinery Manufacturing > Indu...  This industry includes entities that manufactu...
1359           Retail Health and Personal Care Products  Retail > Retail Health and Personal Care Products  This industry includes entities that primarily...
136                                         Photography                Professional Services > Photography  This industry includes entities that provide s...
137                            Human Resources Services  Professional Services > Business Consulting an...  This industry includes entities that provide a...
1370                                    Retail Gasoline                           Retail > Retail Gasoline  This industry includes entities that primarily...
138                             Retail Office Equipment                   Retail > Retail Office Equipment  This industry includes entities that retail of...
139                                  Mental Health Care  Hospitals and Health Care > Medical Practices ...  This industry includes independent mental heal...
14                            Hospitals and Health Care                          Hospitals and Health Care  This industry includes entities that provide h...
140                                      Graphic Design  Professional Services > Design Services > Grap...  This industry includes entities that plan, des...
1407                         Retail Musical Instruments                Retail > Retail Musical Instruments  This industry includes entities that primarily...
1409                      Retail Books and Printed News             Retail > Retail Books and Printed News  This industry includes entities that primarily...
141                 International Trade and Development  Financial Services > Credit Intermediation > I...  This industry includes entities that provide w...
142                              Beverage Manufacturing  Manufacturing > Food and Beverage Manufacturin...  This industry includes entities that manufactu...
1423                                    Retail Florists                           Retail > Retail Florists  This industry includes entities that primarily...
1424                   Retail Office Supplies and Gifts          Retail > Retail Office Supplies and Gifts  This industry includes entities that primarily...
143                     Retail Luxury Goods and Jewelry           Retail > Retail Luxury Goods and Jewelry  This industry includes entities that retail on...
1431     Retail Recyclable Materials & Used Merchandise  Retail > Retail Recyclable Materials & Used Me...  This industry includes entities that primarily...
144        Renewable Energy Semiconductor Manufacturing  Manufacturing > Computers and Electronics Manu...  This industry includes entities that manufactu...
1445                       Online and Mail Order Retail              Retail > Online and Mail Order Retail  This industry includes entities that create an...
145          Glass, Ceramics and Concrete Manufacturing  Manufacturing > Glass, Ceramics and Concrete M...  This industry includes entities that transform...
146              Packaging and Containers Manufacturing  Manufacturing > Plastics and Rubber Product Ma...  This industry includes entities that convert p...
147                  Automation Machinery Manufacturing  Manufacturing > Machinery Manufacturing > Auto...  This industry includes entities that use contr...
148                       Government Relations Services  Professional Services > Advertising Services >...  This industry includes entities aimed at impac...
1481                                Rail Transportation  Transportation, Logistics, Supply Chain and St...  This industry includes entities that primarily...
1495                    Ground Passenger Transportation  Transportation, Logistics, Supply Chain and St...  This industry includes entities that primarily...
1497                             Urban Transit Services  Transportation, Logistics, Supply Chain and St...  This industry includes entities that primarily...
15                         Pharmaceutical Manufacturing  Manufacturing > Chemical Manufacturing > Pharm...  This industry includes entities that: 1. Manuf...
150                                        Horticulture  Farming, Ranching, Forestry > Farming > Hortic...  This industry includes entities that cultivate...
1504                  Interurban and Rural Bus Services  Transportation, Logistics, Supply Chain and St...  This industry includes entities that primarily...
1505                        Taxi and Limousine Services  Transportation, Logistics, Supply Chain and St...  This industry includes entities that primarily...
1512                   School and Employee Bus Services  Transportation, Logistics, Supply Chain and St...  This industry includes entities that primarily...
1517  Shuttles and Special Needs Transportation Serv...  Transportation, Logistics, Supply Chain and St...  This industry includes entities that primarily...
1520                            Pipeline Transportation  Transportation, Logistics, Supply Chain and St...  This industry includes entities that primarily...
1532                         Sightseeing Transportation  Transportation, Logistics, Supply Chain and St...  This industry includes entities that primarily...
1573                                    Postal Services  Transportation, Logistics, Supply Chain and St...  This industry includes government entities tha...
1594                  Technology, Information and Media                  Technology, Information and Media  This industry includes entities that produce t...
16                                  Veterinary Services        Professional Services > Veterinary Services  This industry includes entities of licensed ve...
1600                              Periodical Publishing  Technology, Information and Media > Media and ...  This industry includes entities known either a...
1602                                    Book Publishing  Technology, Information and Media > Media and ...  This industry includes entities known as book ...
1611                         Movies and Sound Recording  Technology, Information and Media > Media and ...  This industry includes entities that primarily...
1623                                    Sound Recording  Technology, Information and Media > Media and ...  This industry includes entities that primarily...
1625                             Sheet Music Publishing  Technology, Information and Media > Media and ...  This industry includes entities that primarily...
1633                  Radio and Television Broadcasting  Technology, Information and Media > Media and ...  This industry includes entities that operate b...
1641                    Cable and Satellite Programming  Technology, Information and Media > Media and ...  This industry includes entities that operate s...
1644                        Telecommunications Carriers  Technology, Information and Media > Media and ...  This industry includes entities that operate, ...
1649                       Satellite Telecommunications  Technology, Information and Media > Media and ...  This industry includes entities that provide t...
1673                              Credit Intermediation         Financial Services > Credit Intermediation  This industry includes entities that primarily...
1678                               Savings Institutions  Financial Services > Credit Intermediation > S...  This industry includes entities that primarily...
1696                                       Loan Brokers  Financial Services > Credit Intermediation > L...  This industry includes entities that primarily...
17                      Medical Equipment Manufacturing    Manufacturing > Medical Equipment Manufacturing  This industry includes entities that manufactu...
1713                 Securities and Commodity Exchanges  Financial Services > Capital Markets > Securit...  This industry includes entities that furnish p...
1720                                  Investment Advice  Financial Services > Capital Markets > Investm...  This industry includes entities that provide c...
1725                                 Insurance Carriers  Financial Services > Insurance > Insurance Car...  This industry includes entities that primarily...
1737                  Insurance Agencies and Brokerages  Financial Services > Insurance > Insurance Age...  This industry includes entities that primarily...

In [ ]:
# Company headcount
# 51-200
# 201-500
# 501-1000
# 1001-5000
# 5001-10,000

# Company type
# Public Company
# Privately Held

# Persona: CXO
# CXO
# Owner / Partner
# Director

# Geography
# North America
url = "https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A4154025850%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACOMPANY_TYPE%2Cvalues%3AList((id%3AC%2Ctext%3APublic%2520Company%2CselectionType%3AINCLUDED)%2C(id%3AP%2Ctext%3APrivately%2520Held%2CselectionType%3AINCLUDED)))%2C(type%3APERSONA%2Cvalues%3AList((id%3A50605714%2Ctext%3ACXO%2CselectionType%3AINCLUDED)))%2C(type%3AREGION%2Cvalues%3AList((id%3A102221843%2Ctext%3ANorth%2520America%2CselectionType%3AINCLUDED)))%2C(type%3ACOMPANY_HEADCOUNT%2Cvalues%3AList((id%3AD%2Ctext%3A51-200%2CselectionType%3AINCLUDED)%2C(id%3AE%2Ctext%3A201-500%2CselectionType%3AINCLUDED)%2C(id%3AF%2Ctext%3A501-1%252C000%2CselectionType%3AINCLUDED)%2C(id%3AG%2Ctext%3A1%252C001-5%252C000%2CselectionType%3AINCLUDED)%2C(id%3AH%2Ctext%3A5%252C001-10%252C000%2CselectionType%3AINCLUDED)))))&sessionId=0s9aiKiDQs29Zer3baFHIw%3D%3D&viewAllFilters=true"