# Imports

In [ ]:
# !sudo /bin/bash -c "(source /venv/bin/activate; pip install --quiet jupyterlab-vim)"
# !jupyter labextension enable

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
# %%
import logging

import pandas as pd

# /venv/lib/python3.12/site-packages/gspread_pandas/spread.py:401: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)` .replace("", np.nan)
pd.set_option("future.no_silent_downcasting", True)

import helpers.hdbg as hdbg
import helpers.henv as henv
import helpers.hprint as hprint

# hcache.get_global_cache_info()
# hcache.clear_global_cache("all")


# %%
hdbg.init_logger(verbosity=logging.INFO)

_LOG = logging.getLogger(__name__)

_LOG.info("%s", henv.get_system_signature()[0])

hprint.config_notebook()

WARNING: Running in Jupyter
INFO  > cmd='/venv/lib/python3.12/site-packages/ipykernel_launcher.py -f /home/.local/share/jupyter/runtime/kernel-1c51d08a-be0d-48e5-9080-b28fde1d0998.json'
INFO  # Git
  branch_name='CmampTask11020_Compute_yamm_stats'
  hash='897195402'
  # Last commits:
    * 897195402 GP Saggese Update                                                            (    2 days ago) Fri Jan 17 02:31:23 2025  (HEAD -> CmampTask11020_Compute_yamm_stats, origin/CmampTask11020_Compute_yamm_stats)
    *   ebba027d6 GP Saggese Merge                                                             (    3 days ago) Thu Jan 16 01:11:29 2025
    |\
    | * 9597ebd88 Shaunak  Dhande CmampTask11196_Build_Dash_data_integration_screen (#11210)        (    3 days ago) Thu Jan 16 00:25:52 2025  (origin/master, origin/HEAD, master)
# Machine info
  system=Linux
  node name=9b21dea71c71
  release=6.10.14-linuxkit
  version=#1 SMP Fri Nov 29 17:22:03 UTC 2024
  machine=aarch64
  processor=aarch64
  cpu count=8
  cpu freq=None
  memory=svmem(total=8218251264, available=7221882880, percent=12.1, used=777875456, free=5462790144, active=1109774336, inactive=680550400, buffers=470786048, cached=1506799616, shared=10657792, slab=811364352)
  disk usage=sdiskusage(total=62671097856, used=59078873088, free=375508992, percent=99.4)
# Packages
  python: 3.12.3
  cvxopt: 1.3.2
  cvxpy: 1.5.3
  gluonnlp: ?
  gluonts: ?
  joblib: 1.4.2
  mxnet: ?
  numpy: 2.1.3
  pandas: 2.2.3
  pyarrow: 18.0.0
  scipy: 1.14.1
  seaborn: 0.13.2
  sklearn: 1.5.2
  statsmodels: 0.14.4

In [34]:
import gspread

print(gspread.__version__)

import gspread_pandas

print(gspread_pandas.__version__)

# gspread_pandas.conf.get_config()
print(gspread_pandas.conf.get_config()["project_id"])

#!sudo /bin/f bash -c "(source /venv/bin/activate; pip install --upgrade google-api-python-client)"

import importlib

import ck_marketing.process_automation.hyamm as cmprauhy

importlib.reload(hyamm)

import ck_marketing.hunterio.hunter_api as cmhuhuap

importlib.reload(cmhuhuap)


# import helpers.hopenai as hopenai

5.12.4
3.3.0
gspread-gp

# Process Contact data

## Read  data

In [ ]:
assert 0

In [26]:
# url = "https://docs.google.com/spreadsheets/d/1nlfOHLUo2iTuNtFb2T5ZJXZZnztAnr3WzG9Jm5lbk6I"
url = "https://docs.google.com/spreadsheets/d/1HanQiolicUToLgQFv1__cPOP4WLks5r7pHcgu2P8BjM"
contact_df = cmprauhy.get_cached_sheet_to_df(url, "Sheet1")
contact_df.set_index("hash", drop=True, inplace=True)
#
cmprauhy.head(contact_df)

INFO  Loading cached version from memory ...
INFO  Loading cached version from memory done (0.101 s)
shape= (7377, 17)
columns= ['origin', 'timestamp', 'first_name', 'last_name', 'email', 'email_verification', 'linkedin_url', 'job_title', 'job_title_description', 'company_name', 'company_domain', 'city', 'stages', 'restrictions', 'industry', 'category', 'notes']

                                              origin                 timestamp first_name     last_name                          email email_verification                         linkedin_url             job_title                              job_title_description             company_name   company_domain                               city stages restrictions industry category notes
hash
00003ef5202fac081d992c3f4cd6d0b9           VC Tier 1                              William  Winkenwerder  wwinkenwerder@tigerglobal.com              valid                                                    Partner                                                     Tiger Global Management  tigerglobal.com  New York, New York, United States
0001a9ecb8aa1721852bcd1817e20ad4  GP_LIn_connections  2024-12-31T15:33:29.238Z     Tyrome         Smith                                                    https://linkedin.com/in/tyromesmith  Principal Consultant  Strategic Advisory and Consulting Services | F...           Go In Now, LLC                      Bowie, Maryland, United States

In [27]:
contact_df = cmprauhy.clean_up_contact_df(contact_df)

                                         0
duplicated_emails         0 / 7377 = 0.00%
remove_invalid_emails     0 / 7377 = 0.00%
remove_chinese_names      0 / 7377 = 0.00%
remove_empty_first_names  0 / 7377 = 0.00%
clean_company_names       0 / 7377 = 0.00%
clean_linkedin_nans       0 / 7377 = 0.00%
clean_linkedin_emails     0 / 7377 = 0.00%
clean_linkedin_websites   0 / 7377 = 0.00%
clean_emails              0 / 7377 = 0.00%

In [28]:
cmprauhy.sanity_check_contact_df(contact_df)

WARNING All columns must be in Contact schema: diff1=set() diff2={'hash'}
{'nan': 0.6325064389318151, 'match': 0.30893317066558224, 'mismatch': 0.058560390402602684}

In [29]:
cmprauhy.print_contact_df_stats(contact_df)

                                     origin timestamp first_name     last_name                          email email_verification linkedin_url job_title job_title_description             company_name   company_domain                               city stages restrictions industry category notes
hash
00003ef5202fac081d992c3f4cd6d0b9  VC Tier 1              William  Winkenwerder  wwinkenwerder@tigerglobal.com              valid                Partner                        Tiger Global Management  tigerglobal.com  New York, New York, United States

                                              0
num_rows                                   7377
count_no_dups              7260 / 7377 = 98.41%
count_no_ascii             7248 / 7260 = 99.83%
count_email                4219 / 7248 = 58.21%
count_email_verification     693 / 7248 = 9.56%
count_name_dups              456 / 7248 = 6.29%
count_origin              7248 / 7248 = 100.00%

In [30]:
contact_df["origin"].value_counts()

origin
GP_LIn_connections          2205
Folkapp                     2093
VCSheet_Query1               878
Search4.FinTech_VC_in_US     868
Euro-VC-LinkedIn             548
VC_search_export             286
VC Tier 1                    251
VC Tier 2                    248
Name: count, dtype: int64

In [31]:
stats_df = cmprauhy.print_contact_df_detailed_stats(contact_df)

## Enrich data

In [39]:
print(contact_df.shape)
contact_df.head(2)

(7377, 17)

                                              origin                 timestamp first_name     last_name                          email email_verification                         linkedin_url             job_title                              job_title_description             company_name   company_domain                               city stages restrictions industry category notes
hash
00003ef5202fac081d992c3f4cd6d0b9           VC Tier 1                              William  Winkenwerder  wwinkenwerder@tigerglobal.com              valid                                                    Partner                                                     Tiger Global Management  tigerglobal.com  New York, New York, United States
0001a9ecb8aa1721852bcd1817e20ad4  GP_LIn_connections  2024-12-31T15:33:29.238Z     Tyrome         Smith                                                    https://linkedin.com/in/tyromesmith  Principal Consultant  Strategic Advisory and Consulting Services | F...           Go In Now, LLC                      Bowie, Maryland, United States

In [103]:
cmprauhy.reset_cache_property()
# hyamm.set_cache_property("enrich", "abort_on_cache_miss", True)
print(cmprauhy.cache_property_to_str("enrich"))

WARNING Resetting cache_property.pkl
# func_name=enrich

In [79]:
cmprauhy.reset_mem_cache()

INFO  Before:
                 memory  disk
enrich                -  7029
enrich_intrinsic      -     0
find_email            -  3740
verify_email          -  4941
INFO  After:
                 memory  disk
enrich                -  7029
enrich_intrinsic      -     0
find_email            -  3740
verify_email          -  4941

In [72]:
cmprauhy.cache_stats_to_str()

                 memory  disk
enrich                -  7029
enrich_intrinsic      -     0
find_email            -  3740
verify_email          -  4941

In [94]:
cmprauhy.force_cache_from_disk()

INFO  Before:
                  memory  disk
enrich              7029  7029
enrich_intrinsic       0     0
find_email          3740  3740
verify_email        4941  4941
INFO  After:
                  memory  disk
enrich              7029  7029
enrich_intrinsic       0     0
find_email          3740  3740
verify_email        4941  4941

In [98]:
first_name = "Tyrome"
last_name = "Smith"
company_name = "Go In Now, LLC"
is_company = True
cmhuhuap.enrich(first_name, last_name, company_name, is_company)
# print(cmhuhuap.enrich)

{'data': {'first_name': None,
  'last_name': None,
  'email': None,
  'score': None,
  'domain': 'go-now.eu',
  'accept_all': None,
  'position': None,
  'twitter': None,
  'linkedin_url': None,
  'phone_number': None,
  'company': None,
  'sources': [],
  'verification': {'date': None, 'status': None}},
 'meta': {'params': {'first_name': 'Tyrome',
   'last_name': 'Smith',
   'full_name': None,
   'domain': None,
   'company': 'Go In Now, LLC',
   'max_duration': None}}}

In [107]:
func_name = "enrich"
cmprauhy.enable_cache_perf(func_name)
# hyamm.set_cache_property(func_name, "abort_on_cache_miss", True)
cmprauhy.set_cache_property(func_name, "report_on_cache_miss", True)

In [108]:
# mode = "AssumeEmailValid"
mode = "FromScratch"
# enrich_kwargs = {"issue_warnings": False}
enrich_kwargs = {}
contact_df2 = cmhuhuap.process_enrich(
    contact_df, "first_name", "last_name", "company_name", mode=mode
)
display(contact_df2.head(2))

  0%|          | 0/7377 [00:00<?, ?it/s]

                                              origin                 timestamp first_name     last_name                          email email_verification                         linkedin_url             job_title                              job_title_description             company_name   company_domain                               city stages restrictions industry category notes    hunterio.company_name hunterio.company_domain                 hunterio.email hunterio.linkedin_url hunterio.job_title
hash
00003ef5202fac081d992c3f4cd6d0b9           VC Tier 1                              William  Winkenwerder  wwinkenwerder@tigerglobal.com              valid                                                    Partner                                                     Tiger Global Management  tigerglobal.com  New York, New York, United States                                              Tiger Global Management         tigerglobal.com  wwinkenwerder@tigerglobal.com                 _nan_              _nan_
0001a9ecb8aa1721852bcd1817e20ad4  GP_LIn_connections  2024-12-31T15:33:29.238Z     Tyrome         Smith                                                    https://linkedin.com/in/tyromesmith  Principal Consultant  Strategic Advisory and Consulting Services | F...           Go In Now, LLC                      Bowie, Maryland, United States                                                                _nan_               go-now.eu                          _nan_                 _nan_              _nan_

In [109]:
print(cmprauhy.get_cache_perf_stats(func_name))
cmprauhy.disable_cache_perf(func_name)

hits=7002 misses=375 tot=7377 hit_rate=0.95

In [ ]:
print(contact_df2.columns)

In [ ]:
cmhuhuap.get_column_stats(
    contact_df2, ["email", "email_verification", "hunterio.email"]
)

In [ ]:
cmprauhy.flush_cache_to_disk()  # "find_email")

In [ ]:
cmprauhy.flush_cache_to_disk()  # "find_email")