# Imports

In [ ]:
# !sudo /bin/bash -c "(source /venv/bin/activate; pip install --quiet jupyterlab-vim)"
# !jupyter labextension enable

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
# %%
import logging

import pandas as pd

# /venv/lib/python3.12/site-packages/gspread_pandas/spread.py:401: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)` .replace("", np.nan)
pd.set_option("future.no_silent_downcasting", True)

import helpers.hdbg as hdbg
import helpers.henv as henv
import helpers.hpandas as hpandas
import helpers.hprint as hprint

# hcache.get_global_cache_info()
# hcache.clear_global_cache("all")


# %%
hdbg.init_logger(verbosity=logging.INFO)

_LOG = logging.getLogger(__name__)

_LOG.info("%s", henv.get_system_signature()[0])

hprint.config_notebook()

WARNING: Running in Jupyter
INFO  > cmd='/venv/lib/python3.12/site-packages/ipykernel_launcher.py -f /home/.local/share/jupyter/runtime/kernel-1c51d08a-be0d-48e5-9080-b28fde1d0998.json'
INFO  # Git
  branch_name='CmampTask11020_Compute_yamm_stats'
  hash='d2293f44a'
  # Last commits:
    * d2293f44a GP Saggese Update                                                            (    3 days ago) Wed Jan 22 00:04:59 2025  (HEAD -> CmampTask11020_Compute_yamm_stats, origin/CmampTask11020_Compute_yamm_stats)
    * 5404856e0 GP Saggese Update                                                            (    3 days ago) Tue Jan 21 19:42:57 2025
    * 9685fb48f GP Saggese Lint                                                              (    5 days ago) Sun Jan 19 23:49:38 2025
# Machine info
  system=Linux
  node name=9b21dea71c71
  release=6.10.14-linuxkit
  version=#1 SMP Fri Nov 29 17:22:03 UTC 2024
  machine=aarch64
  processor=aarch64
  cpu count=8
  cpu freq=None
  memory=svmem(total=8218251264, available=5966913536, percent=27.4, used=2032988160, free=940797952, active=2680557568, inactive=3359092736, buffers=1317167104, cached=3927298048, shared=10514432, slab=1051791360)
  disk usage=sdiskusage(total=62671097856, used=30821879808, free=28632502272, percent=51.8)
# Packages
  python: 3.12.3
  cvxopt: 1.3.2
  cvxpy: 1.5.3
  gluonnlp: ?
  gluonts: ?
  joblib: 1.4.2
  mxnet: ?
  numpy: 2.1.3
  pandas: 2.2.3
  pyarrow: 18.0.0
  scipy: 1.14.1
  seaborn: 0.13.2
  sklearn: 1.5.2
  statsmodels: 0.14.4

In [5]:
import gspread

print(gspread.__version__)

import gspread_pandas

print(gspread_pandas.__version__)

# gspread_pandas.conf.get_config()
print(gspread_pandas.conf.get_config()["project_id"])

#!sudo /bin/f bash -c "(source /venv/bin/activate; pip install --upgrade google-api-python-client)"

import importlib

import ck_marketing.process_automation.hyamm as cmprauhy

importlib.reload(hyamm)

import ck_marketing.hunterio.hunter_api as cmhuhuap

importlib.reload(cmhuhuap)

import ck_marketing.linkedin.linkedin_utils as cmliliut

# import helpers.hopenai as hopenai

5.12.4
3.3.0
gspread-gp

# Load Contact data

In [6]:
contact_dfs = []

## Search4.FinTech_VC_in_US.SalesNavigator

In [41]:
normalize = True
df_tmp = cmprauhy.get_scraped_data_from_LinkedIn(normalize)
contact_dfs.append(df_tmp)

INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1Lbnyvbb28Cv-y0k-nrG1NSES9F6rxesGoHZV2LOJ6wA/' sheet_name='ScrapeProfile'
INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1Lbnyvbb28Cv-y0k-nrG1NSES9F6rxesGoHZV2LOJ6wA/' sheet_name='ScrapeProfile2'
{'timestamp': 'timestamp', 'origin': 'origin', 'linkedinProfileUrl': 'linkedin_url', 'firstName': 'first_name', 'lastName': 'last_name', 'email': 'email', 'jobTitle': 'job_title', 'description': 'job_title_description', 'jobLocation': 'city', 'company': 'company_name'}

In [42]:
cmprauhy.print_contact_df_stats(df_tmp)

  hash                    origin                 timestamp first_name last_name                    email email_verification                                     linkedin_url job_title                              job_title_description    company_name company_domain city stages restrictions industry category notes
0       Search4.FinTech_VC_in_US  2023-11-09T20:34:20.691Z       Adam      Alfi  aalfi@iconiqcapital.com                     https://www.linkedin.com/in/adam-alfi-52891823/   Partner  Partner at ICONIQ / Growth Stage Technology In...  ICONIQ Capital

                                            0
num_rows                                  869
count_no_dups              867 / 869 = 99.77%
count_no_ascii            867 / 867 = 100.00%
count_email                465 / 867 = 53.63%
count_email_verification      0 / 867 = 0.00%
count_name_dups               0 / 867 = 0.00%
count_origin              867 / 867 = 100.00%

## VC_search_export

In [43]:
normalize = True
df_tmp = cmprauhy.get_scraped_data_from_LinkedIn2(normalize)
contact_dfs.append(df_tmp)

  0%|          | 0/11 [00:00<?, ?it/s]

INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1tgKVlDMVJJkPPyulTU1ibkBcGLKXeVjLTYN8jhQ9c3M' sheet_name='hunter_verification'
INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1p7mKeeUuUS4a2OsHnTbWpe5Fscp8mvjocsWRL8ya6PA' sheet_name='hunter_verification'
INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1Iz9ypwENHwSU-meGknkrH_q7Gbg-CK6pArMQcxNvF3s' sheet_name='hunter_verification'
INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1y3bVUkC2qaZWFwkY9xvOcoUnqXEIDEC06mjUdiwXNNc' sheet_name='hunter_verification'
INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1RQMhAOpiu8BTyiNUl9O6DrmovEYAFqPPyBhiPD9uEZA' sheet_name='hunter_verification'
INFO  Reading data from url='https://docs.google.com/spreadsheets/d/197W6s8K4tOzSdoT11rk3huGTxlttzXxpkWruHHzyeDQ' sheet_name='hunter_verification'
INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1xSYf8Hzg7vPmP_pSBe4NMkANX013FuTQR2SJgOr8AqU' sheet_name='hunter_verification'
INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1Gf6dVplfK-ufHoGdY3RchlcapQY2Ig5gopM2YMOTuz4' sheet_name='hunter_verification'
INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1EzsnB-a0cmiWpl2A9-McNrTR4D_jXJY9UB0byy8PuIA' sheet_name='hunter_verification'
INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1Ric5JLQOwkj9m4iwZtSo46VzOI0XDEMdeJZBEO4fPQ8' sheet_name='hunter_verification'
INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1rmImy9VByGf1cNKbYmUVh7ktojtRpXL4QLdvPLAB8C4' sheet_name='hunter_verification'
{'timestamp': 'timestamp', 'origin': 'origin', 'linkedInProfileUrl': 'linkedin_url', 'firstName': 'first_name', 'lastName': 'last_name', 'email': 'email', 'hunter_verification': 'email_verification', 'title': 'job_title', 'titleDescription': 'job_title_description', 'companyName': 'company_name', 'companyLocation': 'city'}

In [44]:
cmprauhy.print_contact_df_stats(df_tmp)

  hash            origin                 timestamp first_name last_name               email email_verification                                       linkedin_url job_title                              job_title_description company_name company_domain                                  city stages restrictions industry category notes
0       VC_search_export  2024-07-11T18:03:01.973Z     Zhenya   Loginov  zloginov@accel.com            _valid_  https://www.linkedin.com/in/ACwAAABGC0cBTaYzMW...   Partner  I invest and help European and Israeli founder...        Accel                 Palo Alto, California, United States

                                            0
num_rows                                  335
count_no_dups              287 / 335 = 85.67%
count_no_ascii             285 / 287 = 99.30%
count_email                220 / 285 = 77.19%
count_email_verification      0 / 285 = 0.00%
count_name_dups               2 / 285 = 0.70%
count_origin              285 / 285 = 100.00%

In [45]:
# hyamm.print_contact_df_detailed_stats(df_tmp)

## Search7.AI_VC_in_US.gsheet

In [46]:
normalize = True
# normalize = False
df_tmp = cmprauhy.get_scraped_data_from_LinkedIn3(normalize)
contact_dfs.append(df_tmp)

INFO  Reading data from url='https://docs.google.com/spreadsheets/d/12qmHUo6sTuFpLQcdw22EaA3xsJ9ERuiCJdhDyF-2elM' sheet_name='test-590999-valid'
{'origin': 'origin', 'linkedinProfileUrl': 'linkedin_url', 'firstName': 'first_name', 'lastName': 'last_name', 'Email': 'email', 'Verification status': 'email_verification', 'Position': 'job_title_description', 'company': 'company_name'}

In [47]:
cmprauhy.print_contact_df_stats(df_tmp)

  hash               origin timestamp first_name last_name           email email_verification                           linkedin_url job_title job_title_description      company_name company_domain city stages restrictions industry category notes
0       Search7.AI_VC_in_US                  Rob     Toews  rob@radical.vc            _valid_  https://www.linkedin.com/in/robtoews/                                  Radical Ventures

                                            0
num_rows                                  197
count_no_dups             197 / 197 = 100.00%
count_no_ascii            197 / 197 = 100.00%
count_email               197 / 197 = 100.00%
count_email_verification      0 / 197 = 0.00%
count_name_dups               0 / 197 = 0.00%
count_origin              197 / 197 = 100.00%

## VC Tier 1 - Partners

In [48]:
normalize = True
df_tmp = cmprauhy.get_scraped_data_from_LinkedIn4(normalize)
contact_dfs.append(df_tmp)

INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1WU_u-4gKDb5NE-u1xwMrkFWDT77PoNQuku0pcj3fbNY/edit?gid=1063998981#gid=1063998981' sheet_name='Sheet1'
INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1WU_u-4gKDb5NE-u1xwMrkFWDT77PoNQuku0pcj3fbNY/edit?gid=1063998981#gid=1063998981' sheet_name='Sheet2'
INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1WU_u-4gKDb5NE-u1xwMrkFWDT77PoNQuku0pcj3fbNY/edit?gid=1063998981#gid=1063998981' sheet_name='Sheet3'
INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1WU_u-4gKDb5NE-u1xwMrkFWDT77PoNQuku0pcj3fbNY/edit?gid=1063998981#gid=1063998981' sheet_name='validity_merged_df'
{'origin': 'origin', 'url': 'linkedin_url', 'first_name': 'first_name', 'last_name': 'last_name', 'email_first': 'email', 'hunter_verification': 'email_verification', 'job_title': 'job_title', 'company_name': 'company_name', 'company_domain': 'company_domain', 'city': 'city'}

In [49]:
cmprauhy.print_contact_df_stats(df_tmp)

  hash     origin timestamp first_name last_name                         email email_verification linkedin_url          job_title job_title_description      company_name       company_domain                               city stages restrictions industry category notes
0       VC Tier 1                Anika   Agarwal  aagarwal@insightpartners.com       _accept_all_          NaN  Managing Director                        Insight Partners  insightpartners.com  New York, New York, United States

                                            0
num_rows                                  551
count_no_dups              315 / 551 = 57.17%
count_no_ascii             290 / 315 = 92.06%
count_email               290 / 290 = 100.00%
count_email_verification      0 / 290 = 0.00%
count_name_dups               7 / 290 = 2.41%
count_origin              290 / 290 = 100.00%

## VC_Tier_2_Partners

In [50]:
normalize = True
df_tmp = cmprauhy.get_scraped_data_from_LinkedIn5(normalize)
contact_dfs.append(df_tmp)

INFO  Reading data from url='https://docs.google.com/spreadsheets/d/17gxl8o_lS9zOsuJMmX1CSZJfZUBx0UZ66eaAlYutfaA/edit?gid=1525085692#gid=1525085692' sheet_name='VC-20240525-1'
INFO  Reading data from url='https://docs.google.com/spreadsheets/d/17gxl8o_lS9zOsuJMmX1CSZJfZUBx0UZ66eaAlYutfaA/edit?gid=1525085692#gid=1525085692' sheet_name='VC-20240520-4'
INFO  Reading data from url='https://docs.google.com/spreadsheets/d/17gxl8o_lS9zOsuJMmX1CSZJfZUBx0UZ66eaAlYutfaA/edit?gid=1525085692#gid=1525085692' sheet_name='VC-20240520-3'
INFO  Reading data from url='https://docs.google.com/spreadsheets/d/17gxl8o_lS9zOsuJMmX1CSZJfZUBx0UZ66eaAlYutfaA/edit?gid=1525085692#gid=1525085692' sheet_name='VC-20240520-2'
INFO  Reading data from url='https://docs.google.com/spreadsheets/d/17gxl8o_lS9zOsuJMmX1CSZJfZUBx0UZ66eaAlYutfaA/edit?gid=1525085692#gid=1525085692' sheet_name='VC-20240520'
{'origin': 'origin', 'First name': 'first_name', 'last_name': 'last_name', 'email_first': 'email', 'email_verification': 'email_verification', 'job_title': 'job_title', 'company_name': 'company_name', 'company_domain': 'company_domain', 'city': 'city'}

In [51]:
cmprauhy.print_contact_df_stats(df_tmp)

  hash     origin timestamp first_name last_name                       email email_verification linkedin_url job_title job_title_description   company_name    company_domain                               city stages restrictions industry category notes
0       VC Tier 2            Rodriguez      Keig  rodriguez@foundersfund.com          _invalid_                Founder                        Founders Fund  foundersfund.com  New York, New York, United States

                                            0
num_rows                                  253
count_no_dups              251 / 253 = 99.21%
count_no_ascii            251 / 251 = 100.00%
count_email               251 / 251 = 100.00%
count_email_verification      0 / 251 = 0.00%
count_name_dups               0 / 251 = 0.00%
count_origin              251 / 251 = 100.00%

## VCSheet

In [52]:
normalize = True
# normalize = False
df_tmp = cmprauhy.get_scraped_data_from_VCSheet(normalize)
contact_dfs.append(df_tmp)

INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1U8jJYZbC1oyZpsSWhCCe6SDpAH8e6R2yRDeFauHVcj0/edit?gid=1769984900#gid=1769984900' sheet_name='Sheet1'
{'origin': 'origin', 'LinkedIn': 'linkedin_url', 'First name': 'first_name', 'last_name': 'last_name', 'Email': 'email', 'Title': 'job_title', 'company_name': 'company_name'}

In [53]:
cmprauhy.print_contact_df_stats(df_tmp)

  hash          origin timestamp first_name last_name              email email_verification                         linkedin_url                      job_title job_title_description company_name company_domain city stages restrictions industry category notes
0       VCSheet_Query1                  Ann  Miura-Ko  ann@floodgate.com                     https://www.linkedin.com/in/amiura/  Co-Founding Partner@Floodgate                          Floodgate

                                            0
num_rows                                  964
count_no_dups             964 / 964 = 100.00%
count_no_ascii             962 / 964 = 99.79%
count_email                890 / 962 = 92.52%
count_email_verification      0 / 962 = 0.00%
count_name_dups               1 / 962 = 0.10%
count_origin              962 / 962 = 100.00%

## Euro-VCs

In [54]:
normalize = True
# normalize = False
df_tmp = cmprauhy.get_scraped_data_from_EuroVC(normalize)
contact_dfs.append(df_tmp)

INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1r3_drVggRB61KvNPxlf58sEwNoUvU_aquLwGLDyUSKI' sheet_name='Sheet1'
(1046, 26)
['Investor', 'Domain', 'Main Country', 'Investor Category', 'Overview', 'Main City', 'Industries', 'Stages', 'Fund Restrictions', 'Fund Restriction Notes', 'Portfolio', 'Categories', 'Second Country', 'Second City', 'Approved', 'Created', 'origin', 'stages', 'restrictions']
Removed 1535 / 2092 = 73.37% rows with empty first name
{'origin': 'origin', 'Linkedin': 'linkedin_url', 'First Name': 'first_name', 'Last Name': 'last_name', 'Email': 'email', 'Title': 'job_title', 'Domain': 'company_name', 'stages': 'stages', 'restrictions': 'restrictions', 'Created': 'timestamp', 'Main City': 'city', 'Overview': 'notes'}

In [55]:
cmprauhy.print_contact_df_stats(df_tmp)

  hash            origin                 timestamp first_name last_name email email_verification                                 linkedin_url                 job_title job_title_description                           company_name company_domain  city                                             stages               restrictions industry category                                              notes
1       Euro-VC-LinkedIn  2020-08-20T16:15:48.000Z     Julian  Zachmann                           https://www.linkedin.com/in/julianzachmann/  Venture Capital Investor                        http://www.high-tech-gruenderfonds.de                 Bonn  Seed,Series A,Series B,Series C,Series D/Ventu...  Must have a tech element.                    High-Tech Grunderfonds (HTGF) is Germany's mos...

                                            0
num_rows                                  557
count_no_dups              556 / 557 = 99.82%
count_no_ascii            556 / 556 = 100.00%
count_email                159 / 556 = 28.60%
count_email_verification      0 / 556 = 0.00%
count_name_dups               2 / 556 = 0.36%
count_origin              556 / 556 = 100.00%

## Folkapp

In [56]:
normalize = True
# normalize = False
df_tmp = cmprauhy.get_scraped_data_from_FolkApp(normalize)
contact_dfs.append(df_tmp)

INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1j6_mI5r05-P6smXMGOq3f0bpmyc7p2W0n7mY8gGbpY0/edit?gid=0#gid=0' sheet_name='Sheet1'
{'origin': 'origin', 'Urls': 'linkedin_url', 'First name': 'first_name', 'last_name': 'last_name', 'Email': 'email', 'Description': 'job_title', 'Companies': 'company_name', 'Fund type': 'category', 'Fund stage': 'stages', 'Fund focus': 'industry', 'Location': 'city'}

In [57]:
cmprauhy.print_contact_df_stats(df_tmp)

  hash   origin timestamp first_name  last_name                     email email_verification                                linkedin_url                                       job_title job_title_description     company_name company_domain       city stages restrictions                              industry      category notes
0       Folkapp                Susan  Akbarpour  susan@candouventures.com                     https://www.linkedin.com/in/susanakbarpour  Investor, Serial entrepreneur and board member                        Candou Ventures                 Palo Alto   Seed               Finance & Crypto;Software & Internet  Venture Fund

                                              0
num_rows                                   2216
count_no_dups             2216 / 2216 = 100.00%
count_no_ascii             2213 / 2216 = 99.86%
count_email                2211 / 2213 = 99.91%
count_email_verification       0 / 2213 = 0.00%
count_name_dups                9 / 2213 = 0.41%
count_origin              2213 / 2213 = 100.00%

## GP_LIn_Connections

In [58]:
normalize = True
# normalize = False
df_tmp = cmprauhy.get_data_from_GP_LIn_connections(normalize)
contact_dfs.append(df_tmp)

INFO  Reading data from url='https://docs.google.com/spreadsheets/d/19ziUmqbPaUO73cqlJB1F9y-j1Oq98nMzo6wTmzyVnwg' sheet_name='Sheet1'
{'origin': 'origin', 'refreshedAt': 'timestamp', 'firstName': 'first_name', 'lastName': 'last_name', 'linkedinProfileUrl': 'linkedin_url', 'linkedinJobTitle': 'job_title', 'job_title_description': 'job_title_description', 'companyName': 'company_name', 'location': 'city', 'companyIndustry': 'category'}

In [59]:
cmprauhy.print_contact_df_stats(df_tmp)

  hash              origin                 timestamp first_name last_name email email_verification                         linkedin_url      job_title                              job_title_description company_name company_domain                              city stages restrictions industry category notes
0       GP_LIn_connections  2024-12-31T02:08:03.137Z  Graham C.      Peck                           https://linkedin.com/in/grahamcpeck  CFO & Partner  Co-Founder @ DealSend & Attaq Vector | Partner...     FYC Labs                 Chicago, Illinois, United States                                Design

                                              0
num_rows                                   2205
count_no_dups              2200 / 2205 = 99.77%
count_no_ascii             2194 / 2200 = 99.73%
count_email                    0 / 2194 = 0.00%
count_email_verification       0 / 2194 = 0.00%
count_name_dups                0 / 2194 = 0.00%
count_origin              2194 / 2194 = 100.00%

# Concat all

In [61]:
contact_df = pd.concat(contact_dfs)
debug = ""
# debug = "duplicated_emails"
# debug = "remove_chinese_names"
# debug = "remove_empty_first_name"
# debug = "clean_company_names"
# debug = "clean_linkedin_emails"
# debug = "clean_linkedin_websites"
contact_df = cmprauhy.clean_up_contact_df(contact_df, debug=debug)
display(contact_df.head(2))

                                              0
duplicated_emails         5114 / 14300 = 35.76%
remove_invalid_emails         40 / 9186 = 0.44%
remove_chinese_names           0 / 9146 = 0.00%
remove_empty_first_names       4 / 9146 = 0.04%
clean_company_names         931 / 9142 = 10.18%
clean_linkedin_nans          198 / 9142 = 2.17%
clean_linkedin_emails          2 / 9142 = 0.02%
clean_linkedin_websites        3 / 9142 = 0.03%
clean_emails                   0 / 9142 = 0.00%

                                              origin                 timestamp first_name     last_name                          email email_verification                         linkedin_url             job_title                              job_title_description             company_name   company_domain                               city stages restrictions industry category notes
hash
00003ef5202fac081d992c3f4cd6d0b9           VC Tier 1                              William  Winkenwerder  wwinkenwerder@tigerglobal.com            _valid_                                                    Partner                                                     Tiger Global Management  tigerglobal.com  New York, New York, United States
0001a9ecb8aa1721852bcd1817e20ad4  GP_LIn_connections  2024-12-31T15:33:29.238Z     Tyrome         Smith                                                    https://linkedin.com/in/tyromesmith  Principal Consultant  Strategic Advisory and Consulting Services | F...           Go In Now, LLC                      Bowie, Maryland, United States

In [62]:
cmprauhy.print_contact_df_detailed_stats(contact_df)

In [63]:
cmprauhy.sanity_check_contact_df(contact_df)

WARNING All columns must be in Contact schema: diff1=set() diff2={'hash'}
{'nan': 0.7049879676219646, 'match': 0.2477576022752133, 'mismatch': 0.04725443010282214}

In [64]:
cmprauhy.print_contact_df_stats(contact_df)

                                     origin timestamp first_name     last_name                          email email_verification linkedin_url job_title job_title_description             company_name   company_domain                               city stages restrictions industry category notes
hash
00003ef5202fac081d992c3f4cd6d0b9  VC Tier 1              William  Winkenwerder  wwinkenwerder@tigerglobal.com            _valid_                Partner                        Tiger Global Management  tigerglobal.com  New York, New York, United States

                                              0
num_rows                                   9142
count_no_dups              7354 / 9142 = 80.44%
count_no_ascii             7343 / 7354 = 99.85%
count_email                4379 / 7343 = 59.64%
count_email_verification       0 / 7343 = 0.00%
count_name_dups              460 / 7343 = 6.26%
count_origin              7343 / 7343 = 100.00%

In [65]:
contact_df["origin"].value_counts()

origin
GP_LIn_connections          2205
Search4.FinTech_VC_in_US    2077
Folkapp                     2074
VCSheet_Query1               950
Euro-VC-LinkedIn             946
VC Tier 1                    251
VC Tier 2                    248
VC_search_export             216
Search7.AI_VC_in_US          175
Name: count, dtype: int64

In [ ]:
cmprauhy.save_to_gsheet(contact_df)

# Process Contact data

## Read  data

In [ ]:
assert 0

In [66]:
# url = "https://docs.google.com/spreadsheets/d/1nlfOHLUo2iTuNtFb2T5ZJXZZnztAnr3WzG9Jm5lbk6I"
url = "https://docs.google.com/spreadsheets/d/1HanQiolicUToLgQFv1__cPOP4WLks5r7pHcgu2P8BjM"
contact_df = cmprauhy.get_cached_sheet_to_df(url, "Sheet1")
contact_df.set_index("hash", drop=True, inplace=True)
#
cmprauhy.head(contact_df)

INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1HanQiolicUToLgQFv1__cPOP4WLks5r7pHcgu2P8BjM' sheet_name='Sheet1'
shape= (7377, 17)
columns= ['origin', 'timestamp', 'first_name', 'last_name', 'email', 'email_verification', 'linkedin_url', 'job_title', 'job_title_description', 'company_name', 'company_domain', 'city', 'stages', 'restrictions', 'industry', 'category', 'notes']

                                              origin                 timestamp first_name     last_name                          email email_verification                         linkedin_url             job_title                              job_title_description             company_name   company_domain                               city stages restrictions industry category notes
hash
00003ef5202fac081d992c3f4cd6d0b9           VC Tier 1                              William  Winkenwerder  wwinkenwerder@tigerglobal.com              valid                                                    Partner                                                     Tiger Global Management  tigerglobal.com  New York, New York, United States
0001a9ecb8aa1721852bcd1817e20ad4  GP_LIn_connections  2024-12-31T15:33:29.238Z     Tyrome         Smith                                                    https://linkedin.com/in/tyromesmith  Principal Consultant  Strategic Advisory and Consulting Services | F...           Go In Now, LLC                      Bowie, Maryland, United States

In [67]:
contact_df = cmprauhy.clean_up_contact_df(contact_df)

                                         0
duplicated_emails         0 / 7377 = 0.00%
remove_invalid_emails     0 / 7377 = 0.00%
remove_chinese_names      0 / 7377 = 0.00%
remove_empty_first_names  0 / 7377 = 0.00%
clean_company_names       0 / 7377 = 0.00%
clean_linkedin_nans       0 / 7377 = 0.00%
clean_linkedin_emails     0 / 7377 = 0.00%
clean_linkedin_websites   0 / 7377 = 0.00%
clean_emails              0 / 7377 = 0.00%

In [68]:
cmprauhy.sanity_check_contact_df(contact_df)

WARNING All columns must be in Contact schema: diff1=set() diff2={'hash'}
{'nan': 0.6325064389318151, 'match': 0.30893317066558224, 'mismatch': 0.058560390402602684}

In [229]:
cmprauhy.print_contact_df_stats(contact_df)

                                     origin timestamp first_name     last_name                          email email_verification linkedin_url job_title job_title_description             company_name   company_domain                               city stages restrictions industry category notes
hash
00003ef5202fac081d992c3f4cd6d0b9  VC Tier 1              William  Winkenwerder  wwinkenwerder@tigerglobal.com              valid                Partner                        Tiger Global Management  tigerglobal.com  New York, New York, United States

                                              0
num_rows                                   7377
count_no_dups              7260 / 7377 = 98.41%
count_no_ascii             7248 / 7260 = 99.83%
count_email                4219 / 7248 = 58.21%
count_email_verification     693 / 7248 = 9.56%
count_name_dups              456 / 7248 = 6.29%
count_origin              7248 / 7248 = 100.00%

In [30]:
contact_df["origin"].value_counts()

origin
GP_LIn_connections          2205
Folkapp                     2093
VCSheet_Query1               878
Search4.FinTech_VC_in_US     868
Euro-VC-LinkedIn             548
VC_search_export             286
VC Tier 1                    251
VC Tier 2                    248
Name: count, dtype: int64

In [31]:
stats_df = cmprauhy.print_contact_df_detailed_stats(contact_df)

## Clean up names

In [35]:
contact_df = cmliliut.clean_and_track_name_changes(contact_df)

debug_df = cmliliut.get_debug_clean_name_df(contact_df)
cmliliut.get_clean_name_stats(contact_df)

                                 first_name     last_name cleaned_first_name first_alias cleaned_last_name second_alias  is_modified
hash
00003ef5202fac081d992c3f4cd6d0b9    William  Winkenwerder            William                  Winkenwerder                     False
0001a9ecb8aa1721852bcd1817e20ad4     Tyrome         Smith             Tyrome                         Smith                     False
0006449606c198dc8b7c7f28f9100d03     Joshua        Siegel             Joshua                        Siegel                     False

                                   0
is_modified       497 / 7377 = 6.74%
empty_first_name    3 / 7377 = 0.04%
empty_last_name    13 / 7377 = 0.18%
has_alias          43 / 7377 = 0.58%

In [38]:
hpandas.filter_df(debug_df, "is_modified", True).head(2)

INFO  selected=497 / 7377 = 6.74%

                                 first_name last_name cleaned_first_name first_alias cleaned_last_name second_alias  is_modified
hash
015d26a696a949d8126b31c7fe9ed3d4     ALBERT       SYE             Albert                           Sye                      True
0169100f7a5488f875e19e318c90113a     Eric D     Kroll               Eric                         Kroll                      True

In [36]:
contact_df = cmliliut.merge_clean_names_df(contact_df)

contact_df.head(1)

                                     origin timestamp first_name     last_name                          email email_verification linkedin_url job_title job_title_description             company_name   company_domain                               city stages restrictions industry category notes
hash
00003ef5202fac081d992c3f4cd6d0b9  VC Tier 1              William  Winkenwerder  wwinkenwerder@tigerglobal.com              valid                Partner                        Tiger Global Management  tigerglobal.com  New York, New York, United States

## Enrich data

In [39]:
print(contact_df.shape)
contact_df.head(2)

(7377, 17)

                                              origin                 timestamp first_name     last_name                          email email_verification                         linkedin_url             job_title                              job_title_description             company_name   company_domain                               city stages restrictions industry category notes
hash
00003ef5202fac081d992c3f4cd6d0b9           VC Tier 1                              William  Winkenwerder  wwinkenwerder@tigerglobal.com              valid                                                    Partner                                                     Tiger Global Management  tigerglobal.com  New York, New York, United States
0001a9ecb8aa1721852bcd1817e20ad4  GP_LIn_connections  2024-12-31T15:33:29.238Z     Tyrome         Smith                                                    https://linkedin.com/in/tyromesmith  Principal Consultant  Strategic Advisory and Consulting Services | F...           Go In Now, LLC                      Bowie, Maryland, United States

In [132]:
# mode = "AssumeEmailValid"
mode = "FromScratch"
# dry_run = True
dry_run = False
# enrich_kwargs = {"issue_warnings": False}
enrich_kwargs = {}
contact_df2 = cmhuhuap.process_enrich(
    contact_df,
    "first_name",
    "last_name",
    "company_name",
    mode=mode,
    dry_run=dry_run,
)
display(contact_df2.head(1))

  0%|          | 0/7377 [00:00<?, ?it/s]

                                     origin timestamp first_name     last_name                          email email_verification linkedin_url job_title job_title_description             company_name   company_domain                               city stages restrictions industry category notes    hunterio.company_name hunterio.company_domain                 hunterio.email hunterio.linkedin_url hunterio.job_title
hash
00003ef5202fac081d992c3f4cd6d0b9  VC Tier 1              William  Winkenwerder  wwinkenwerder@tigerglobal.com              valid                Partner                        Tiger Global Management  tigerglobal.com  New York, New York, United States                                              Tiger Global Management         tigerglobal.com  wwinkenwerder@tigerglobal.com                 _nan_              _nan_

In [126]:
print(contact_df2.columns)

Index(['origin', 'timestamp', 'first_name', 'last_name', 'email', 'email_verification', 'linkedin_url', 'job_title', 'job_title_description', 'company_name', 'company_domain', 'city', 'stages', 'restrictions', 'industry', 'category', 'notes', 'hunterio.company_name', 'hunterio.company_domain', 'hunterio.email', 'hunterio.linkedin_url', 'hunterio.job_title'], dtype='object')

In [170]:
cmprauhy.get_column_stats(
    contact_df2,
    ["email", "email_verification", "hunterio.email"],
    info_mode="only_pct",
)

                   num_vals num_unique_vals num_empty_vals num_tokens unique_tokens
email                  7377          57.27%         42.74%      0.00%            0
email_verification     7377           0.07%         90.61%      0.00%            0
hunterio.email         7377          51.69%         15.71%     28.82%       1 _nan_

In [166]:
cmprauhy.flush_cache_to_disk()  # "find_email")

INFO  Before:
                 memory  disk
enrich                -  7029
enrich_intrinsic      -     0
find_email            -  3740
verify_email          -  4941
INFO  After:
                  memory  disk
enrich              7029  7029
enrich_intrinsic       0     0
find_email          3740  3740
verify_email        4941  4941

In [ ]:
cmprauhy.flush_cache_to_disk()  # "find_email")

## Merge Hunter.io enrichment

In [172]:
print(contact_df2.columns)

Index(['origin', 'timestamp', 'first_name', 'last_name', 'email', 'email_verification', 'linkedin_url', 'job_title', 'job_title_description', 'company_name', 'company_domain', 'city', 'stages', 'restrictions', 'industry', 'category', 'notes', 'hunterio.company_name', 'hunterio.company_domain', 'hunterio.email', 'hunterio.linkedin_url', 'hunterio.job_title'], dtype='object')

In [173]:
del contact_df_enriched

In [174]:
contact_df3 = cmhuhuap.merge_hunterio_values(contact_df2)

In [175]:
cmprauhy.sanity_check_contact_df(contact_df3)

WARNING All columns must be in Contact schema: diff1=set() diff2={'hash'}
{'match': 0.6254575030500203, 'nan': 0.2826352175681171, 'mismatch': 0.09190727938186255}

In [176]:
print(contact_df3.columns)

Index(['origin', 'timestamp', 'first_name', 'last_name', 'email', 'email_verification', 'linkedin_url', 'job_title', 'job_title_description', 'company_name', 'company_domain', 'city', 'stages', 'restrictions', 'industry', 'category', 'notes'], dtype='object')

In [177]:
cmprauhy.head(contact_df3, num_rows=2)

shape= (7377, 17)
columns= ['origin', 'timestamp', 'first_name', 'last_name', 'email', 'email_verification', 'linkedin_url', 'job_title', 'job_title_description', 'company_name', 'company_domain', 'city', 'stages', 'restrictions', 'industry', 'category', 'notes']

                                              origin                 timestamp first_name     last_name                          email email_verification                         linkedin_url             job_title                              job_title_description             company_name   company_domain                               city stages restrictions industry category notes
hash
00003ef5202fac081d992c3f4cd6d0b9           VC Tier 1                              William  Winkenwerder  wwinkenwerder@tigerglobal.com              valid                                _nan_               Partner                                                     Tiger Global Management  tigerglobal.com  New York, New York, United States
0001a9ecb8aa1721852bcd1817e20ad4  GP_LIn_connections  2024-12-31T15:33:29.238Z     Tyrome         Smith                          _nan_                     https://linkedin.com/in/tyromesmith  Principal Consultant  Strategic Advisory and Consulting Services | F...           Go In Now, LLC        go-now.eu     Bowie, Maryland, United States

In [179]:
cmprauhy.get_column_stats(contact_df3, ["email", "email_verification"])

                   num_vals num_unique_vals num_empty_vals num_tokens unique_tokens
email                  7377          71.03%          0.00%     25.82%       1 _nan_
email_verification     7377           0.07%         90.61%      0.00%            0

In [180]:
stats_df = cmprauhy.print_contact_df_detailed_stats(contact_df3)

In [ ]:
# hyamm.save_to_gsheet(contact_df_enriched, name="contact_df_enriched")

## Infer category

In [181]:
cmprauhy.get_value_counts_stats_df(contact_df3, "category")

                                   count    pct [%]
category
                                    3328  45.113190
Venture Fund                        1893  25.660838
Financial Services                   490   6.642267
Venture Capital & Private Equity     315   4.270028
Computer Software                    288   3.904026
Higher Education                     243   3.294022
Information Technology & Services    127   1.721567
Accelerator                           72   0.976007
Corporate VC                          66   0.894673
Management Consulting                 34   0.460892

In [183]:
contact_df_tmp = cmprauhy.infer_category(contact_df3)

                            num    pct [%]
tag
stages                     2635  35.719127
partner_in_job             2431  32.953775
venture_in_name            1677  22.732818
capital_in_company_name    1231  16.687000
vc_in_domain                885  11.996747
venture_in_job              548   7.428494
director_in_job             505   6.845601
invest_in_job               418   5.666260
vc_in_name                  152   2.060458
vc_in_job                    50   0.677782
scout_in_job_title           31   0.420225
in_residence_in_job_title    16   0.216890
eir_in_job_title              2   0.027111

       count    pct [%]
is_vc
0       4531  61.420632
1       1179  15.982107
2        989  13.406534
3        504   6.832046
4        160   2.168903
5         14   0.189779

## Validate email

In [230]:
cmhuhuap.get_account_info()

{'searches': {'used': 5000, 'available': 5000, 'over_quota': 1927},
 'verifications': {'used': 7004, 'available': 10000, 'over_quota': 0},
 'reset_date': '2025-01-25'}

In [202]:
contact_df4 = contact_df3.copy()
print(contact_df4.shape)
contact_df4.head(2)

(7377, 17)

                                              origin                 timestamp first_name     last_name                          email email_verification                         linkedin_url             job_title                              job_title_description             company_name   company_domain                               city stages restrictions industry category notes
hash
00003ef5202fac081d992c3f4cd6d0b9           VC Tier 1                              William  Winkenwerder  wwinkenwerder@tigerglobal.com              valid                                _nan_               Partner                                                     Tiger Global Management  tigerglobal.com  New York, New York, United States
0001a9ecb8aa1721852bcd1817e20ad4  GP_LIn_connections  2024-12-31T15:33:29.238Z     Tyrome         Smith                          _nan_                     https://linkedin.com/in/tyromesmith  Principal Consultant  Strategic Advisory and Consulting Services | F...           Go In Now, LLC        go-now.eu     Bowie, Maryland, United States

In [203]:
cmprauhy.print_contact_df_stats(contact_df4)

                                     origin timestamp first_name     last_name                          email email_verification linkedin_url job_title job_title_description             company_name   company_domain                               city stages restrictions industry category notes
hash
00003ef5202fac081d992c3f4cd6d0b9  VC Tier 1              William  Winkenwerder  wwinkenwerder@tigerglobal.com              valid        _nan_   Partner                        Tiger Global Management  tigerglobal.com  New York, New York, United States

                                              0
num_rows                                   7377
count_no_dups              7078 / 7377 = 95.95%
count_no_ascii            7078 / 7078 = 100.00%
count_email                5251 / 7078 = 74.19%
count_email_verification     667 / 7078 = 9.42%
count_name_dups              291 / 7078 = 4.11%
count_origin              7078 / 7078 = 100.00%

In [205]:
cmprauhy.enable_cache_perf("verify_email")
mode = "AssumeEmailValid"
dry_run = True
is_company = True
contact_df5 = cmhuhuap.process_email(
    contact_df4,
    "first_name",
    "last_name",
    "company_name",
    is_company,
    mode=mode,
    dry_run=dry_run,
)

WARNING Resetting cache_property.pkl
WARNING Computing stats for 'find_email'
# func_name=find_email
report_on_cache_miss: True
WARNING Computing stats for 'verify_email'
# func_name=verify_email
report_on_cache_miss: True

  0%|          | 0/7377 [00:00<?, ?it/s]

find_email: hits=0 misses=0 tot=0 hit_rate=0.00
verify_email: hits=3940 misses=3437 tot=7377 hit_rate=0.53

In [208]:
cmprauhy.save_to_gsheet(contact_df5)

https://docs.google.com/spreadsheets/d/1elmXgDiZ5Vp8PyoAxW14ovND9zRUIdjKnrjBVG-gXJU
INFO  Saved to display_tmp

In [206]:
cmprauhy.print_contact_df_stats(contact_df5)

                                     origin timestamp first_name     last_name                          email email_verification linkedin_url job_title job_title_description             company_name   company_domain                               city stages restrictions industry category notes                 hunterio.email hunterio.email_verification
hash
00003ef5202fac081d992c3f4cd6d0b9  VC Tier 1              William  Winkenwerder  wwinkenwerder@tigerglobal.com              valid        _nan_   Partner                        Tiger Global Management  tigerglobal.com  New York, New York, United States                                              wwinkenwerder@tigerglobal.com                       valid

                                              0
num_rows                                   7377
count_no_dups              7078 / 7377 = 95.95%
count_no_ascii            7078 / 7078 = 100.00%
count_email                5251 / 7078 = 74.19%
count_email_verification     667 / 7078 = 9.42%
count_name_dups              291 / 7078 = 4.11%
count_origin              7078 / 7078 = 100.00%

In [ ]:
# diagnostics_df = cmhuhuap.get_diagnostic_df(contact_df_tmp)
# display(diagnostics_df.head(2))

# import pprint
# pprint.pprint(cmhuhuap.get_stats(diagnostics_df), sort_dicts=False)

In [ ]:
cmprauhy.force_cache_from_disk()

In [ ]:
cmprauhy.flush_cache_to_disk()  # "find_email")

In [ ]:
print(cmprauhy.cache_stats_to_str())

In [207]:
cols = [
    "first_name",
    "last_name",
    "email",
    "company_name",
    "hunterio.email",
    "is_email_changed",
]
mask = contact_df_tmp["is_email_changed"]
contact_df_tmp.loc[mask][cols]

NameError: name 'contact_df_tmp' is not defined

In [ ]:
contact_df_tmp["hunterio.email_verification"].unique()

## Check category

In [ ]:
contact_df_tmp2 = contact_df_tmp.copy()
display(contact_df_tmp2.head(1))

In [ ]:
cmprauhy.get_value_counts_stats_df(contact_df_tmp2, "category", num_rows=20)

In [ ]:
# categories = ["Venture Fund (inferred)", "Venture Fund", "Venture Capital & Private Equity", "Accelerator", "Corporate VC", "Family Office"]
# contact_df_tmp2 = hpandas.filter_df(contact_df_tmp2, "category", categories)
# contact_df_tmp2 = hpandas.filter_df(contact_df_tmp2, "email", "_nan_", invert=True)

In [ ]:
# hpandas.filter_df(contact_df_tmp2, "category", "").head(3)

In [ ]:
contact_df_tmp2 = hpandas.filter_df(
    contact_df_tmp2, "category", ["Financial Services", "Family Office"]
)
# contact_df_tmp2 = hpandas.filter_df(contact_df_tmp2, "email", "_nan_", invert=True)
# mask = contact_df_tmp2["company_name"].isin(["Engineers Gate", "Teza Technologies", "RavenPack"])
# contact_df_tmp2 = contact_df_tmp2[~mask]

In [ ]:
cmprauhy.sanity_check_contact_df(contact_df_tmp2)

In [ ]:
mode = "AssumeEmailValid"
contact_df_tmp3 = cmhuhuap.process_email(
    contact_df_tmp2,
    "first_name",
    "last_name",
    "company_name",
    mode=mode,
    is_company=True,
)

contact_df_tmp3["email_verification"] = contact_df_tmp3[
    "hunterio.email_verification"
]

In [ ]:
contact_df_tmp3.head()

In [ ]:
cmprauhy.save_to_gsheet(contact_df_tmp3, name="financial")

In [ ]:
cmprauhy.get_value_counts_stats_df(contact_df_tmp3, "origin", num_rows=20)

In [ ]:
contact_df = contact_df_tmp3

# YAMM pipeline

## Read and merge data

In [ ]:
yamm_df = cmprauhy.get_yamm_results()

In [ ]:
display(yamm_df.head(3))

In [ ]:
yamm_df["campaign_name"].unique()

In [ ]:
cmprauhy.yamm_stats_to_pct(yamm_df)

In [ ]:
cmprauhy.yamm_stats_by_campaign(yamm_df)

In [ ]:
# hyamm.save_to_gsheet(yamm_df)

## Load data

In [ ]:
url = "https://docs.google.com/spreadsheets/d/1KosRM5j6cFz8mm3Aw-ctIncAPOLx5bF1bkcEFrHnJsY"
yamm_df = cmprauhy.get_cached_sheet_to_df(url, "Sheet1")
print(yamm_df.shape)
display(yamm_df.head(5))

In [ ]:
# hyamm.yamm_stats(yamm_df)
cmprauhy.yamm_stats_to_pct(yamm_df)

## Update Contact_df with YAMM data

In [ ]:
print(contact_df.shape)
contact_yamm_df = cmprauhy.update_contact_df_with_yamm_df(contact_df, yamm_df)
print(contact_yamm_df.shape)

In [ ]:
# campaign_name = "campaign0_VC_causify"
campaign_name = "campaign2_VC_UMD"
# Pick the one already sent.
# df_tmp = hpandas.filter_df(contact_yamm_df, campaign_name, "", invert=True)
df_tmp = hpandas.filter_df(contact_yamm_df, campaign_name, "", invert=False)
cmprauhy.get_short_contact_df(df_tmp)

In [ ]:
# mask = yamm_df["campaign_name"] == "campaign2_VC_UMD"
# print(mask.sum())

In [ ]:
# mask2 = contact_yamm_df["campaign2_VC_UMD"] != ""
# print(mask2.sum())

# Extract YAMM / LIN campaign

In [ ]:
assert 0

In [ ]:
# campaign_col_name = "campaign0_VC_causify"
# campaign_col_name = "campaign1_VC_causify"
campaign_col_name = "campaign2_VC_UMD"
type_ = "email"
# type_ = "linkedin"
# num_rows = 10
num_rows = -1
campaign_df, contact_df2 = cmprauhy.select_campaign(
    contact_yamm_df, campaign_col_name, type_, num_rows, seed=2
)

In [ ]:
contact_df2.head(2)

In [ ]:
hpandas.filter_df(contact_df2, campaign_col_name, "selected").head(2)

In [ ]:
print(campaign_df.shape)
campaign_df.head()

In [ ]:
cmprauhy.save_to_gsheet(campaign_df, name="campaign_3_LIN_VC")

# One-offs

In [ ]:
#
(
    "Wave1-20241210-folkapp1",
    "campaign0_VC_causify",
    "https://docs.google.com/spreadsheets/d/1mwRy0yTTCnTR14npWe7xATBYLb7DV9Pt1a2p4DjloQA",
    ["YAMM-20241210", "YAMM-20241210-1", "YAMM-20241210-2"],
),
#
(
    "Wave2-20241210-folkapp1",
    "campaign0_VC_causify",
    "https://docs.google.com/spreadsheets/d/1eufg2XREYbXnCy8tygGKAkDigM0OE_fJRmnHTDxFQ8A",
    ["YAMM-2024-12-"],
),
#
(
    "campaign_1_batch1",
    "campaign1_VC_causify",
    "https://docs.google.com/spreadsheets/d/10bWbYHdzl5KvvccHI5grtquFraO29MFP3iBcwkuVj1A",
    ["Sheet1", "Sheet2"],
),
#
(
    "Campaign2_UMD_YAMM",
    "campaign2_VC_UMD",
    "https://docs.google.com/spreadsheets/d/1rpM5MeMtAwRvbV1fCngKD4"
    "-xe7Wc19ikvs7ljx9HIeA",
    ["2024-12-28"],
),

In [ ]:
# url = "https s://docs.google.com/spreadsheets/d/1rpM5MeMtAwRvbV1fCngKD4-xe7Wc19ikvs7ljx9HIeA"
# url = "https://docs.google.com/spreadsheets/d/1mwRy0yTTCnTR14npWe7xATBYLb7DV9Pt1a2p4DjloQA"
url = "https://docs.google.com/spreadsheets/d/1eufg2XREYbXnCy8tygGKAkDigM0OE_fJRmnHTDxFQ8A"
gsheet_name = "YAMM-2024-12-"
df = cmprauhy.get_cached_sheet_to_df(url, gsheet_name)
# display(df.head(3))

res_df = df.merge(
    contact_df, left_on="email", right_on="email", how="left"
)  # [["hash"] + df.columns.tolist()]
hash_ = res_df["hash"]
res_df = df.copy()
res_df.insert(0, "hash", hash_)

res_df.head()

In [ ]:
hpandas.filter_df(res_df, "hash", "", check_value=False)

In [ ]:
cmprauhy.save_to_gsheet(res_df, name="test1")

In [209]:
url = "https://docs.google.com/spreadsheets/d/1zJtF9q6NC9hEM3arUxr7vzVNmSyfxrybcYNkOaisjC4/edit?gid=796026511#gid=796026511"
df = cmprauhy.get_cached_sheet_to_df(url, "SaaS Angel Investors (Globally)")

INFO  Updating cached version on disk ...
INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1zJtF9q6NC9hEM3arUxr7vzVNmSyfxrybcYNkOaisjC4/edit?gid=796026511#gid=796026511' sheet_name='SaaS Angel Investors (Globally)'
INFO  Updating cached version on disk done (2.265 s)

In [211]:
cmprauhy.save_to_gsheet(df)

https://docs.google.com/spreadsheets/d/1NIEidp8tiBFkrs-TEwLla5Zj4EjoyckxUrfHAUQ_olM
INFO  Saved to display_tmp