In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [27]:
# %%
import datetime
import logging
import os
import re

import pandas as pd
# /venv/lib/python3.12/site-packages/gspread_pandas/spread.py:401: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)` .replace("", np.nan)
pd.set_option('future.no_silent_downcasting', True)

import helpers.hdbg as hdbg
import helpers.henv as henv
import helpers.hpandas as hpandas
import helpers.hprint as hprint
import helpers.hcache as hcache

#hcache.get_global_cache_info()
#hcache.clear_global_cache("all")

import config_root.config as cconfig

# %%
hdbg.init_logger(verbosity=logging.INFO)

_LOG = logging.getLogger(__name__)

_LOG.info("%s", henv.get_system_signature()[0])

hprint.config_notebook()

WARNING: Logger already initialized: skipping
INFO  # Git
  branch_name='CmampTask11020_Compute_yamm_stats'
  hash='50f413699'
  # Last commits:
    *   50f413699 GP Saggese Merge branch 'master' into CmampTask11020_Compute_yamm_stats      (70 minutes ago) Wed Jan 8 23:11:29 2025  (HEAD -> CmampTask11020_Compute_yamm_stats, origin/CmampTask11020_Compute_yamm_stats)
    |\
    * | 91b7ff63d GP Saggese Update                                                            (70 minutes ago) Wed Jan 8 23:11:23 2025
    | * b682dff49 Dan      Cm task11040 remove get universe from im client 8 (#11164)        (   4 hours ago) Wed Jan 8 20:27:04 2025  (origin/master, origin/HEAD, master)
# Machine info
  system=Linux
  node name=a835e9cd7a0d
  release=6.6.22-linuxkit
  version=#1 SMP Fri Mar 29 12:21:27 UTC 2024
  machine=aarch64
  processor=aarch64
  cpu count=8
  cpu freq=None
  memory=svmem(total=8222072832, available=6460047360, percent=21.4, used=1552101376, free=2254422016, active=1914208256, inactive=3219775488, buffers=676159488, cached=3739389952, shared=2076672, slab=688914432)
  disk usage=sdiskusage(total=62671097856, used=59077668864, free=376713216, percent=99.4)
# Packages
  python: 3.12.3
  cvxopt: 1.3.2
  cvxpy: 1.5.3
  gluonnlp: ?
  gluonts: ?
  joblib: 1.4.2
  mxnet: ?
  numpy: 2.1.3
  pandas: 2.2.3
  pyarrow: 18.0.0
  scipy: 1.14.1
  seaborn: 0.13.2
  sklearn: 1.5.2
  statsmodels: 0.14.4

In [3]:
import gspread
print(gspread.__version__)

import gspread_pandas
print(gspread_pandas.__version__)

#gspread_pandas.conf.get_config()
print(gspread_pandas.conf.get_config()["project_id"])

#!sudo /bin/f bash -c "(source /venv/bin/activate; pip install --upgrade google-api-python-client)"

import importlib
import ck_marketing.process_automation.hyamm as hyamm
importlib.reload(hyamm)

# import ck_marketing.hunterio.hunter_api as cmhuhuap
# importlib.reload(cmhuhuap)

#import helpers.hopenai as hopenai

5.12.4
3.3.0
gspread-gp

/app/ck_marketing/process_automation/hyamm.py:19: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm

# Read data

In [38]:
#url = "https://docs.google.com/spreadsheets/d/1nlfOHLUo2iTuNtFb2T5ZJXZZnztAnr3WzG9Jm5lbk6I"
#url = "https://docs.google.com/spreadsheets/d/1NCBbacXYEjnXtPBO1gn937lOUmum4Fvfw-fRxz5wvmY"
url = "https://docs.google.com/spreadsheets/d/1wuCds_rPTqjlu5mTUOKQC3pNBVXurTTZPdX5ryQr3wA"
contact_df = hyamm.get_cached_sheet_to_df(url, "Sheet3")
contact_df.set_index("hash", drop=True, inplace=True)
print(contact_df.shape)
display(contact_df.head(2))

INFO  Updating cached version on disk ...
INFO  Reading data from url='https://docs.google.com/spreadsheets/d/1wuCds_rPTqjlu5mTUOKQC3pNBVXurTTZPdX5ryQr3wA' sheet_name='Sheet3'
INFO  Updating cached version on disk done (2.314 s)
(607, 19)

                                   origin timestamp first_name last_name                             email email_verification linkedin_url job_title job_title_description company_name                  company_domain              city stages restrictions                                           industry       category notes                    hunterio.email hunterio.email_verification
hash
4a4079215e5eccf89e6089f7dd6574f7  Folkapp                David    Rossow  david.rossow@gatesfoundation.org              valid        _nan_     _nan_                              _nan_  http://www.gatesfoundation.org          New York  FALSE               Health;Industry;Food;Consulting & Services;Sof...  Family Office        david.rossow@gatesfoundation.org                       valid
bf436a1cde88d1e0079a889081d32f88  Folkapp                 Jeff    Ehlers                jehlers@dnscap.com              valid        _nan_     _nan_                              _nan_                  www.dnscap.com  Chicago;Illinois  FALSE               Software & Internet;AI & Machine Learning;Logi...  Family Office                      jehlers@dnscap.com                       valid

In [39]:
import ck_marketing.linkedin.linkedin_utils as cmliliut

In [40]:
df = contact_df.head(1000)

#df["first_name"].apply(lambda x : cmliliut.clean_first_last_name(x, last_name_only=False))
#df["last_name"].apply(lambda x : cmliliut.clean_first_last_name(x, last_name_only=True))

In [41]:
# Define a wrapper function to handle precedence of nicknames.
def process_names(row) -> pd.Series:
    first_name_cleaned, first_nickname = cmliliut.clean_first_last_name(
        row["first_name"], last_name_only=False
    )
    last_name_cleaned, last_nickname = cmliliut.clean_first_last_name(
        row["last_name"], last_name_only=True
    )
    m = re.match(r'^(\w+)\S+\s', first_name_cleaned)
    if m:
        first_name_cleaned = m.group(0)
    # Choose the nickname with precedence given to the first name.
    return pd.Series([first_name_cleaned, last_name_cleaned, first_nickname, last_nickname])


# Apply the processing function.
df_first_last = df.copy()
df_first_last[
    ["cleaned_first_name", "cleaned_last_name", "first_nickname", "last_nickname"]
] = df_first_last.apply(process_names, axis=1)
# _LOG.info(
#     "Separate transformation =\n %s",
#     hpandas.df_to_str(df_first_last, log_level=logging.WARNING),
# )


df_first_last["is_modified"] = (df_first_last["first_name"] != df_first_last["cleaned_first_name"]) | (df_first_last["last_name"] != df_first_last["cleaned_last_name"])

col_names = "origin first_name last_name cleaned_first_name cleaned_last_name first_nickname last_nickname is_modified".split()
df_first_last[col_names].head()

                                   origin first_name  last_name cleaned_first_name cleaned_last_name first_nickname last_nickname  is_modified
hash
4a4079215e5eccf89e6089f7dd6574f7  Folkapp      David     Rossow              David            Rossow                                     False
bf436a1cde88d1e0079a889081d32f88  Folkapp       Jeff     Ehlers               Jeff            Ehlers                                     False
b95b4cb1a59603c67b1e1f6b4f29c81b  Folkapp     Jeremy  Schneider             Jeremy         Schneider                                     False
45f4d41f6ddf5919c35f0fecf614fa6c  Folkapp    Michael        Kam            Michael               Kam                                     False
aabc181457c8785fd6e1858a1ad7d1cd  Folkapp     Pierre    Omidyar             Pierre           Omidyar                                     False

In [42]:
df_tmp = df_first_last
hpandas.filter_df(df_tmp, "is_modified", True)[col_names]

INFO  selected=165 / 607 = 27.18%

                                              origin         first_name                         last_name cleaned_first_name cleaned_last_name first_nickname last_nickname  is_modified
hash
38d81474c9c9563df1ccb47d92ccac1a  GP_LIn_connections               Todd                     Bendell, CFP®               Todd           Bendell                                      True
e96f296f531b6919da878ee1cd0b08a7     hedge_fund_list           Nancy A.                           Kukacka             Nancy            Kukacka                                      True
cdf15b6eea41b8392a3532ccbf2cc147  GP_LIn_connections         Francis X.                        Frecentese           Francis         Frecentese                                      True
a1336845ba79bfc95c3ed4461df5795e     hedge_fund_list          Thomas E.                           Claugus            Thomas            Claugus                                      True
5e193c3c7b1dd661d1e48cfb3d505d7c  GP_LIn_connections          Stephanie                      Rumold, CFP®          Stephanie            Rumold                                      True
e6f35e35d6d684289e48d05a4a174bd1     hedge_fund_list            John D.                        Gottfurcht              John         Gottfurcht                                      True
dd9f78e9dc5dcf9278e79701c76a3af6  GP_LIn_connections            Kristin               Milchanowski, Ph.D.            Kristin      Milchanowski                                      True
60b1271693297e93da9b7805512099f6  GP_LIn_connections            Jose M.                      Plehn, Ph.D.              Jose              Plehn                                      True
52f76202800ca6ee141f5090e80feee2     hedge_fund_list            John P.                           Calamos              John            Calamos                                      True
1a8686e869e13467a264d4105cc2b6d6     hedge_fund_list     Christopher S.                             Wight       Christopher              Wight                                      True
1803d137166b6edb39f907c0d1b983e4  GP_LIn_connections           James C.                               Row             James                Row                                      True
04dc8de7f1880f24558d9714a7e10d68  GP_LIn_connections          Christine                         Cai,  FRM          Christine               Cai                                      True
5b0260db1ff78e7dcaea017473f53243     hedge_fund_list           Philippe                      Laffont, CFA           Philippe           Laffont                                      True
5b829d4f316972fc2abf62f3f254c7f6     hedge_fund_list        Martha P.E.                           Arscott            Martha            Arscott                                      True
88d48a512b3da11263c9ed9df6c9e79d     hedge_fund_list           David G.                           Arscott             David            Arscott                                      True
c37ffe274c7d41a9260e2617bc713851     hedge_fund_list           Alain S,                            Harrus             Alain             Harrus                                      True
10672c65f78a351ee53908df38fe6a72     hedge_fund_list             Ronald                           McGlynn             Ronald           Mcglynn                                      True
649a3f6ff6ce83e7ccd63bd9136a8652  GP_LIn_connections    Paromita (Paro)                         Guha, PhD           Paromita              Guha           Paro                       True
9d7f3037cf3f36e6fb5daf7372bcfcd1     hedge_fund_list             Thomas                           kempner             Thomas           Kempner                                      True
29cef59d212a831912e1611fd2fc1291  GP_LIn_connections            Phillip                        Moran, CFA            Phillip             Moran                                      True
4eec0f1b37a373b4bff1e46884ed696e  GP_LIn_connections                Sam                        Tegel, CFA                Sam             Tegel                                      True
901ea9930444d612b0ccf30f8192bc11     hedge_fund_list              Ricky                      Sandler, CFA              Ricky           Sandler                                      True
2405633686ed966520d6b80c607dc6de  GP_LIn_connections                Ian                          McDonald                Ian          Mcdonald                                      True
2c0467ea967adbcfa539ddad511a6043     hedge_fund_list          Joseph C.                             McNay            Joseph              Mcnay                                      True
7d875826e129fa7c076c0fa6bb8cae1b     hedge_fund_list         Jeffrey T.                            Harris           Jeffrey             Harris                                      True
264a52106ac5313f2e2ececd5ab9e8e7     hedge_fund_list          Steven J.                             Byrne            Steven              Byrne                                      True
8ceb63a560f5e59ab9183c85e0ade72e  GP_LIn_connections             Curtis                         MacDonald             Curtis         Macdonald                                      True
ce2e11cfcecffad01b4b05d51d1819e1  GP_LIn_connections           Frederic                           GEORJON           Frederic           Georjon                                      True
afaba2b2aa035670e25fc940a30156ca  GP_LIn_connections              Denis                      Suvorov, CFA              Denis           Suvorov                                      True
5ce6fbeb1c4331c979d13315e5f43f63  GP_LIn_connections        Dr. Richard                          Peterson            Richard          Peterson                                      True
e02f4de3b31ad599911bdf89c02ddc7c  GP_LIn_connections              Monty                   Joshi, CFA, CFP              Monty             Joshi                                      True
4ead64cbf58d4b6dd25253ec4ff8d861     hedge_fund_list           Scott L.                            Miller             Scott             Miller                                      True
27231c8325e1c948b2747417bbd17fab  GP_LIn_connections              Daryl                        Smith, CFA              Daryl             Smith                                      True
e0f6d622d399591829cc093682f98bf4  GP_LIn_connections              Pooja                        Malik, CFA              Pooja             Malik                                      True
1148965e207b2a385112c6c734cbb21e  GP_LIn_connections             Giulio                       Gatti, CAIA             Giulio             Gatti                                      True
d86d10791bd9871c9f46bc952f40675c  GP_LIn_connections              Taras                       Klinchik 🇺🇦              Taras          Klinchik                                      True
5addc9151df314a06713c600c580d375  GP_LIn_connections          Alexander                        Burns, CFA          Alexander             Burns                                      True
116ead4dced987b38be8832e2ea28b40  GP_LIn_connections               Jack                             DuBro               Jack             Dubro                                      True
f583b8ec0e824a303bec643edf7e4440  GP_LIn_connections         C. Augusto                           Proiete          C Augusto           Proiete                                      True
792c9586e8f3bd5c19f2c6aac8254abf     hedge_fund_list         Douglas A.                              Haws           Douglas               Haws                                      True
db0d25cc9bd7b28d5b52d45bdf72b2a0  GP_LIn_connections              Marco  Berna, CEO VIM Wealth Management              Marco             Berna                                      True
f6f329d828bbebe83fc56367788412a8     hedge_fund_list          Joseph A.                            McGraw            Joseph             Mcgraw                                      True
8494161f0eedb50d34350b1b02b15322     hedge_fund_list            A. Gary                          Shilling             A Gary          Shilling                                      True
5709b6b881bd13496d72a0e94967953f     hedge_fund_list          Martin J.                           Whitman            Martin            Whitman                                      True
556dfe31d5e4cf640666b438f5385e89             Folkapp                Don                        MacDougall                Don        Macdougall                                      True
c5b1819b414162d1cb2920b6516bc084     hedge_fund_list         Richard J.                              Keim           Richard               Keim                                      True
22247386b3637f69c7a028f17ea45586     hedge_fund_list          Thomas E.                           Claugus            Thomas            Claugus                                      True
d92bd85a3ab4898ad781516ca6ec369c     hedge_fund_list          Razmig E.                          Bulujian            Razmig           Bulujian                                      True
4eb9f88ade1e7bff8c57d866c730482a     hedge_fund_list           Peter B.                              Cook             Peter               Cook                                      True
6a918a8784fe4ff799eaac8099d89dfb     hedge_fund_list         Charles L.                            Minter           Charles             Minter                                      True
fc16695be04080279e36683f68aeaef1     hedge_fund_list          Joseph W.                            Daniel            Joseph             Daniel                                      True
cf61f843f493843db9fe75e904a71354     hedge_fund_list         William A.                          Douglass           William           Douglass                                      True
2edf853d36ad01654691e65a5d13b86b     hedge_fund_list          Robert S.                           Robbins            Robert            Robbins                                      True
6d4faa6ef9014781676005d142630c9e     hedge_fund_list            Marc A.                       Pentopoulos              Marc        Pentopoulos                                      True
78dddbced853e1fd5726a815c1be97b4     hedge_fund_list         Matthew P.                         Spotswood           Matthew          Spotswood                                      True
873c02a21c834077036429fc3877b1c1     hedge_fund_list         Michael T.                           Jackson           Michael            Jackson                                      True
e82a0988aa233ed3b46eef5408246d3f     hedge_fund_list              james                            Bitzer              James            Bitzer                                      True
e2c0c6b20e0d6c85c4853de97a267c40     hedge_fund_list          Thomas R.                             Baker            Thomas              Baker                                      True
ba8215d416da36c937f2d4d54ca55782     hedge_fund_list         Kenneth B.                           Funsten           Kenneth            Funsten                                      True
cfcdb241ddb7316a2910f967533734c8     hedge_fund_list         M. Michael                            Ansour          M Michael            Ansour                                      True
4b6b8c68f6ddf4908b4925ecf71aad11     hedge_fund_list         Dr. Conrad                           Seghers             Conrad           Seghers                                      True
c71861de61af62b401bd37ab3636bb6a     hedge_fund_list            Paul A.                            Henley              Paul             Henley                                      True
e6ca0a324bad3e848facf950b7a2e631     hedge_fund_list               Neil                            O'Hara               Neil            O'hara                                      True
b116c4c4e3249882b1aed73b4b918b6d  GP_LIn_connections              Mário                  Albuquerque, CFA              Mario       Albuquerque                                      True
d7abdce27ecf2407dbb69b828b67b98d     hedge_fund_list            John A.                            O'Hara              John             O'hara                                      True
e1306c931afa6addce706e7626c7da00     hedge_fund_list           Brian E.                            Divney             Brian             Divney                                      True
a7aa306a1599a475b3fc1fb88fa6e9c4     hedge_fund_list            Gene R.                          Tremblay              Gene           Tremblay                                      True
0763965aca72af3f1dd84fa338b5af6b     hedge_fund_list         Richard B.                           Steward           Richard            Steward                                      True
ecda46e1904c1e46f0afe924bdc851c1  GP_LIn_connections              Erick                  Calder (えりくかぇでる)              Erick            Calder                                      True
33072b84bd504a56e475117e0a8cc8b8     hedge_fund_list           Jason R.                     Graybill, CFA             Jason           Graybill                                      True
1b411c72c25b32a91ab23c5ba97d230d     hedge_fund_list          Thomas H.                        Nolan, Jr.            Thomas              Nolan                                      True
5bd665c6fc29f7ee59fcc39dbf56309f     hedge_fund_list         Matthew A.                           Troxell           Matthew            Troxell                                      True
2c154e43832a374117233776675134af  GP_LIn_connections                Dan                 Joldzic, CFA, FRM                Dan           Joldzic                                      True
1a61a24315345b76cce224df2988551e  GP_LIn_connections               Neil                         St. Clair               Neil          St Clair                                      True
1dcb5a183de2e3cbece85ba9147470ef     hedge_fund_list         Stephen J.                           Summers           Stephen            Summers                                      True
865aaeb5f38033c63473251c9e6145eb     hedge_fund_list         Jeffrey E.                           Schwarz           Jeffrey            Schwarz                                      True
c1c033df44eadd536056966818955885     hedge_fund_list          Ronald E.                            Elijah            Ronald             Elijah                                      True
eefe1af96d3e5cabad18694fd8a4fe79     hedge_fund_list           Clint D.                           Carlson             Clint            Carlson                                      True
411a57e434cac10ea5c34f420aa3ee6a  GP_LIn_connections            Gerardo                      Manzo, Ph.D.            Gerardo             Manzo                                      True
2876680c9759cf6eb3b8f22a926a1888  GP_LIn_connections           A. Blake                            Cooper            A Blake            Cooper                                      True
e48e59be9563306d79bc4da54c35b8d1     hedge_fund_list         Raymond T.                             Dalio           Raymond              Dalio                                      True
b5b4e106736871adf0a9de3c1729ad1f     hedge_fund_list         William C.    Horne, Dir. Of Client Services           William              Horne                                      True
b18fada884a794bad53aa4366256c5aa     hedge_fund_list          Samuel D.                             Isaly            Samuel              Isaly                                      True
6f5fadc65ff00b62d44b4fb4bcb4c0cd     hedge_fund_list              Chris                       Guthrie CFA              Chris       Guthrie Cfa                                      True
5a0a5b1588feabd0f1544c4350fe2789     hedge_fund_list        Mitchell R.                             Julis          Mitchell              Julis                                      True
6f44aef333c7ff8a07cc64bf7945c42b     hedge_fund_list             Donald                         Laing III             Donald         Laing Iii                                      True
0df6ad69945e652208f828826b5c52e1  GP_LIn_connections         Matthew C.                          Pilsbury           Matthew           Pilsbury                                      True
5b9eaeecf1934f9b8501b0e6f82300e1  GP_LIn_connections              Scott                      Meadows, CFA              Scott           Meadows                                      True
37dee39d75c4e36ab4dd6d68355c1f3b     hedge_fund_list        Dr. Jens M.                            Kothes              Jens             Kothes                                      True
21bd81f4cba0b144c16deafd3f5b8040     hedge_fund_list            Neil P.                            Ramsey              Neil             Ramsey                                      True
d7c863533aca040eb6d2c93e3f11d296     hedge_fund_list           David E.                              Shaw             David               Shaw                                      True
ee3994ab4a657147f2cf69f022226aaa     hedge_fund_list            John G.                             Goode              John              Goode                                      True
f2126471ddfa48acd5095b4cdb713aa6     hedge_fund_list           Peter J.                             Hable             Peter              Hable                                      True
f1c873cd1ac6286df80ce8734c34f904     hedge_fund_list           Harry S.                              Dent             Harry               Dent                                      True
079608940b6511b17a5e97515afecea6     hedge_fund_list             Andrew                        St. Pierre             Andrew         St Pierre                                      True
384ec8a76d3b051accb57492c362b2f6     hedge_fund_list            Michael                           DiCarlo            Michael           Dicarlo                                      True
fd733210696b1e70126cd838ef7fb524     hedge_fund_list               Gary                      di Silvestri               Gary      Di Silvestri                                      True
733585b5e7050102744e40e36e97235e     hedge_fund_list         Stewart H.                        Greenfield           Stewart         Greenfield                                      True
c6c822f4d0a74cf99a3cd7bf68b716a4     hedge_fund_list          J. Robert                           Dobbins           J Robert           Dobbins                                      True
1f00347ac37edbf0c1aef222286ec515     hedge_fund_list           C. Bryan                      Cameron, CFA            C Bryan           Cameron                                      True
210c10e145a95e4f7a0978beb8b360af     hedge_fund_list            John A.                         Gunn, CFA              John               Gunn                                      True
56c01e50eaccf87e9d042c41a19e7746     hedge_fund_list          Steven C.                           Voorhis            Steven            Voorhis                                      True
704ed59aeea45daedb9d11f7a1d96dbd     hedge_fund_list           David C.                             Hoeft             David              Hoeft                                      True
7c238c44fbf6d372190ff80a1d73a793     hedge_fund_list            John N.                       Iannuccillo              John        Iannuccillo                                      True
8a5895ba2aafe65379bdb531089a29c5     hedge_fund_list            Lynn A.                             Poole              Lynn              Poole                                      True
93d7298fd82cbb0552d9d20bafb53425     hedge_fund_list          Katherine                Herrick Drake, CFA          Katherine     Herrick Drake                                      True
975aad222fad303c6e3c49cb489eca71     hedge_fund_list          Steven H.                          Cassriel            Steven           Cassriel                                      True

In [43]:
hyamm.save_to_gsheet(df_first_last, name="financial2")

https://docs.google.com/spreadsheets/d/1W8lWkaoSyX5uODoJtjiujKjijWD_I1ZrvXx7e_H5j3Y
INFO  Saved to financial2