In [1]:
import gspread

print(gspread.__version__)

import gspread_pandas

print(gspread_pandas.__version__)

5.12.4
3.3.0

In [5]:
!sudo /bin/bash -c "(source /venv/bin/activate; pip install --upgrade google-api-python-client)"

Collecting google-api-python-client
  Downloading google_api_python_client-2.156.0-py2.py3-none-any.whl.metadata (6.7 kB)
Collecting httplib2<1.dev0,>=0.19.0 (from google-api-python-client)
  Downloading httplib2-0.22.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0 in /venv/lib/python3.12/site-packages (from google-api-python-client) (2.36.0)
Collecting google-auth-httplib2<1.0.0,>=0.2.0 (from google-api-python-client)
  Downloading google_auth_httplib2-0.2.0-py2.py3-none-any.whl.metadata (2.2 kB)
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5 (from google-api-python-client)
  Downloading google_api_core-2.24.0-py3-none-any.whl.metadata (3.0 kB)
Collecting uritemplate<5,>=3.0.1 (from google-api-python-client)
  Downloading uritemplate-4.1.1-py2.py3-none-any.whl.metadata (2.9 kB)
Collecting googleapis-common-protos<2.0.dev0,>=1.56.2 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client)
  Downloading googleapis_common_protos-1.66.0-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.19.5 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client)
  Downloading protobuf-5.29.2-cp38-abi3-manylinux2014_x86_64.whl.metadata (592 bytes)
Collecting proto-plus<2.0.0dev,>=1.22.3 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client)
  Downloading proto_plus-1.25.0-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in /venv/lib/python3.12/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2.32.3)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /venv/lib/python3.12/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client) (5.5.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /venv/lib/python3.12/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /venv/lib/python3.12/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client) (4.2)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /venv/lib/python3.12/site-packages (from httplib2<1.dev0,>=0.19.0->google-api-python-client) (3.2.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /venv/lib/python3.12/site-packages (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client) (0.6.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /venv/lib/python3.12/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /venv/lib/python3.12/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /venv/lib/python3.12/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /venv/lib/python3.12/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2024.8.30)
Downloading google_api_python_client-2.156.0-py2.py3-none-any.whl (12.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 104.7 MB/s eta 0:00:0000:0100:01
Downloading google_api_core-2.24.0-py3-none-any.whl (158 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.6/158.6 kB 9.9 MB/s eta 0:00:00
Downloading google_auth_httplib2-0.2.0-py2.py3-none-any.whl (9.3 kB)
Downloading httplib2-0.22.0-py3-none-any.whl (96 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.9/96.9 kB 5.5 MB/s eta 0:00:00
Downloading uritemplate-4.1.1-py2.py3-none-any.whl (10 kB)
Downloading googleapis_common_protos-1.66.0-py2.py3-none-any.whl (221 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 221.7/221.7 kB 12.6 MB/s eta 0:00:00
Downloading proto_plus-1.25.0-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 kB 3.6 MB/s eta 0:00:00
Downloading protobuf-5.29.2-cp38-abi3-manylinux2014_x86_64.whl (319 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.7/319.7 kB 17.3 MB/s eta 0:00:00
Installing collected packages: uritemplate, protobuf, httplib2, proto-plus, googleapis-common-protos, google-auth-httplib2, google-api-core, google-api-python-client
Successfully installed google-api-core-2.24.0 google-api-python-client-2.156.0 google-auth-httplib2-0.2.0 googleapis-common-protos-1.66.0 httplib2-0.22.0 proto-plus-1.25.0 protobuf-5.29.2 uritemplate-4.1.1

In [53]:
import importlib

import helpers.hgoogle_file_api as hgofiapi

importlib.reload(hgofiapi)

In [23]:
creds = hgofiapi.get_credentials()

In [24]:
creds

In [25]:
sheet_id = "13hAmJ58Ois4CcxDoeP-Pwu_JR8kb11wcGHEaDQ5h_Gg"

In [28]:
df_signalnfx = hgofiapi.read_google_sheet(sheet_id)

In [29]:
df_signalnfx.head()

,fullName,companyName,companyPosition,sweetSpot,rangePrice
0,Marc Andreessen,Andreessen Horowitz,General Partner,Sweet spot: $20.0M,Range: $500K - $40.0M
1,Pete Flint,NFX,General Partner,Sweet spot: $2.5M,Range: $500K - $5.0M
2,Aaref Hilaly,Bain Capital Ventures,Partner,Sweet spot: $10.0M,Range: $1M - $100.0M
3,James Currier,NFX,General Partner,Sweet spot: $2.5M,Range: $500K - $4.0M
4,Peter Thiel,Founders Fund,Managing Partner,Sweet spot: $10.0M,Range: $1M - $20.0M

In [59]:
import ck_marketing.hunterio.hunter_api as cmhuhuap

importlib.reload(cmhuhuap)

In [32]:
df_signalnfx[["firstName", "lastName"]] = df_signalnfx["fullName"].str.split(
    " ", n=1, expand=True
)

In [34]:
hgofiapi.write_sheet(df_signalnfx, sheet_id, "cleaned_profiles")

In [47]:
cmhuhuap.find_bulk_emails(
    df_signalnfx, "firstName", "lastName", "companyName", incremental=False
)

Column 'hunterio_email' already exists in DataFrame. Overwriting values.

  0%|          | 0/4878 [00:00<?, ?it/s]

Error fetching email for Jana Messerschmidt at #ANGELS (Hashtag ANGELS): 401 Client Error: Unauthorized for url: https://api.hunter.io/v2/email-finder?company=#ANGELS%20(Hashtag%20ANGELS)&first_name=Jana&last_name=Messerschmidt&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
Error fetching email for Qiang "Larry"  Li at AMINO Capital: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-finder?company=AMINO%20Capital&first_name=Qiang&last_name=%22Larry%22%20%20Li&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
Error fetching email for Q Motiwala at DNX Ventures: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-finder?company=DNX%20Ventures&first_name=Q&last_name=Motiwala&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
Error fetching email for J Seth Strattan PhD at Two Bear Capital: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-finder?company=Two%20Bear%20Capital&first_name=J&last_name=Seth%20Strattan%20PhD&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
Error fetching email for Alexis Robert at Kima Ventures: 451 Client Error: Unavailable For Legal Reasons for url: https://api.hunter.io/v2/email-finder?company=Kima%20Ventures&first_name=Alexis&last_name=Robert&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
Error fetching email for Ryan C at Hive Ventures: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-finder?company=Hive%20Ventures&first_name=Ryan&last_name=C&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
Error fetching email for Navi S. at Antler: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-finder?company=Antler&first_name=Navi&last_name=S.&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
Error fetching email for Bijoy B. at FiDi Ventures: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-finder?company=FiDi%20Ventures&first_name=Bijoy&last_name=B.&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
Error fetching email for Erik L. at 1-4-All Group: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-finder?company=1-4-All%20Group&first_name=Erik&last_name=L.&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
Error fetching email for Ursula E. at Beacon Angels: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-finder?company=Beacon%20Angels&first_name=Ursula&last_name=E.&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
Error fetching email for Eda Taskin at Antler: 502 Server Error: Bad Gateway for url: https://api.hunter.io/v2/email-finder?company=Antler&first_name=Eda&last_name=Taskin&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
Error fetching email for Ritabrata M. at Antler: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-finder?company=Antler&first_name=Ritabrata&last_name=M.&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
Error fetching email for Johann "Hansi" Hansmann at N/A: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-finder?company=N/A&first_name=Johann&last_name=%22Hansi%22%20Hansmann&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
Error fetching email for Humayun H. at N/A: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-finder?company=N/A&first_name=Humayun&last_name=H.&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
Error fetching email for George C. at ff Venture Capital: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-finder?company=ff%20Venture%20Capital&first_name=George&last_name=C.&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
Error fetching email for Kyle D at Glasswing Ventures: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-finder?company=Glasswing%20Ventures&first_name=Kyle&last_name=D&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
Error fetching email for Daniel G at N/A: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-finder?company=N/A&first_name=Daniel&last_name=G&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
Error fetching email for Michael Beutner at N/A: 502 Server Error: Bad Gateway for url: https://api.hunter.io/v2/email-finder?company=N/A&first_name=Michael&last_name=Beutner&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
Error fetching email for S J at N/A: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-finder?company=N/A&first_name=S&last_name=J&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
Error fetching email for Sreeraman M G at N/A: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-finder?company=N/A&first_name=Sreeraman&last_name=M%20G&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
Error fetching email for Amrish S. at N/A: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-finder?company=N/A&first_name=Amrish&last_name=S.&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16

,fullName,companyName,companyPosition,sweetSpot,rangePrice,firstName,lastName,hunterio_email
0,Marc Andreessen,Andreessen Horowitz,General Partner,Sweet spot: $20.0M,Range: $500K - $40.0M,Marc,Andreessen,marc@a16z.com
1,Pete Flint,NFX,General Partner,Sweet spot: $2.5M,Range: $500K - $5.0M,Pete,Flint,pete@nfx.com
2,Aaref Hilaly,Bain Capital Ventures,Partner,Sweet spot: $10.0M,Range: $1M - $100.0M,Aaref,Hilaly,None
3,James Currier,NFX,General Partner,Sweet spot: $2.5M,Range: $500K - $4.0M,James,Currier,james@nfx.com
4,Peter Thiel,Founders Fund,Managing Partner,Sweet spot: $10.0M,Range: $1M - $20.0M,Peter,Thiel,peter@foundersfund.com
...,...,...,...,...,...,...,...,...
4873,Sagi Schliesser,N/A,$100K,Sweet spot: $100K,Range: $25K - $250K,Sagi,Schliesser,None
4874,Louis Perrochon,N/A,$0,Sweet spot: $0,Range: $0 - $0,Louis,Perrochon,None
4875,Gregory Miller,N/A,$0,Sweet spot: $0,Range: $0 - $0,Gregory,Miller,None
4876,Chien Yu,N/A,$3K,Sweet spot: $3K,Range: $1K - $10K,Chien,Yu,None
4877,Malin-Iulian Stefanescu,N/A,$50K,Sweet spot: $50K,Range: $10K - $100K,Malin-Iulian,Stefanescu,None

In [48]:
# df_signalnfx = df_signalnfx.drop(columns=["hunterio_email"])

In [49]:
df_signalnfx.head()

,fullName,companyName,companyPosition,sweetSpot,rangePrice,firstName,lastName,hunterio_email
0,Marc Andreessen,Andreessen Horowitz,General Partner,Sweet spot: $20.0M,Range: $500K - $40.0M,Marc,Andreessen,marc@a16z.com
1,Pete Flint,NFX,General Partner,Sweet spot: $2.5M,Range: $500K - $5.0M,Pete,Flint,pete@nfx.com
2,Aaref Hilaly,Bain Capital Ventures,Partner,Sweet spot: $10.0M,Range: $1M - $100.0M,Aaref,Hilaly,None
3,James Currier,NFX,General Partner,Sweet spot: $2.5M,Range: $500K - $4.0M,James,Currier,james@nfx.com
4,Peter Thiel,Founders Fund,Managing Partner,Sweet spot: $10.0M,Range: $1M - $20.0M,Peter,Thiel,peter@foundersfund.com

In [50]:
hgofiapi.write_sheet(df_signalnfx, sheet_id, "hunter_email")

In [60]:
incremental = False
# email = "hunterio_email"
email = "hunterio_email"
cmhuhuap.verify_bulk_emails(df_signalnfx, email, incremental=incremental)

Column 'hunterio_verification' already exists in DataFrame. Overwriting values.

  0%|          | 0/4878 [00:00<?, ?it/s]

Invalid email input: None
Error verifying email victoria.ferguson@mmcventures.com: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

,fullName,companyName,companyPosition,sweetSpot,rangePrice,firstName,lastName,hunterio_email,hunterio_verification
0,Marc Andreessen,Andreessen Horowitz,General Partner,Sweet spot: $20.0M,Range: $500K - $40.0M,Marc,Andreessen,marc@a16z.com,accept_all
1,Pete Flint,NFX,General Partner,Sweet spot: $2.5M,Range: $500K - $5.0M,Pete,Flint,pete@nfx.com,valid
2,Aaref Hilaly,Bain Capital Ventures,Partner,Sweet spot: $10.0M,Range: $1M - $100.0M,Aaref,Hilaly,None,error
3,James Currier,NFX,General Partner,Sweet spot: $2.5M,Range: $500K - $4.0M,James,Currier,james@nfx.com,valid
4,Peter Thiel,Founders Fund,Managing Partner,Sweet spot: $10.0M,Range: $1M - $20.0M,Peter,Thiel,peter@foundersfund.com,accept_all
...,...,...,...,...,...,...,...,...,...
4873,Sagi Schliesser,N/A,$100K,Sweet spot: $100K,Range: $25K - $250K,Sagi,Schliesser,None,error
4874,Louis Perrochon,N/A,$0,Sweet spot: $0,Range: $0 - $0,Louis,Perrochon,None,error
4875,Gregory Miller,N/A,$0,Sweet spot: $0,Range: $0 - $0,Gregory,Miller,None,error
4876,Chien Yu,N/A,$3K,Sweet spot: $3K,Range: $1K - $10K,Chien,Yu,None,error
4877,Malin-Iulian Stefanescu,N/A,$50K,Sweet spot: $50K,Range: $10K - $100K,Malin-Iulian,Stefanescu,None,error

In [61]:
df_signalnfx.head()

,fullName,companyName,companyPosition,sweetSpot,rangePrice,firstName,lastName,hunterio_email,hunterio_verification
0,Marc Andreessen,Andreessen Horowitz,General Partner,Sweet spot: $20.0M,Range: $500K - $40.0M,Marc,Andreessen,marc@a16z.com,accept_all
1,Pete Flint,NFX,General Partner,Sweet spot: $2.5M,Range: $500K - $5.0M,Pete,Flint,pete@nfx.com,valid
2,Aaref Hilaly,Bain Capital Ventures,Partner,Sweet spot: $10.0M,Range: $1M - $100.0M,Aaref,Hilaly,None,error
3,James Currier,NFX,General Partner,Sweet spot: $2.5M,Range: $500K - $4.0M,James,Currier,james@nfx.com,valid
4,Peter Thiel,Founders Fund,Managing Partner,Sweet spot: $10.0M,Range: $1M - $20.0M,Peter,Thiel,peter@foundersfund.com,accept_all

In [62]:
hgofiapi.write_sheet(df_signalnfx, sheet_id, "email_verification")

In [64]:
cmhuhuap.process(
    df_signalnfx,
    "firstName",
    "lastName",
    "companyName",
    "hunterio_email",
    "hunterio_verification",
    is_company=True,
)

  0%|          | 0/4878 [00:00<?, ?it/s]

In [65]:
df_signalnfx.head()

,fullName,companyName,companyPosition,sweetSpot,rangePrice,firstName,lastName,hunterio_email,hunterio_verification
0,Marc Andreessen,Andreessen Horowitz,General Partner,Sweet spot: $20.0M,Range: $500K - $40.0M,Marc,Andreessen,marc@a16z.com,accept_all
1,Pete Flint,NFX,General Partner,Sweet spot: $2.5M,Range: $500K - $5.0M,Pete,Flint,pete@nfx.com,valid
2,Aaref Hilaly,Bain Capital Ventures,Partner,Sweet spot: $10.0M,Range: $1M - $100.0M,Aaref,Hilaly,None,error
3,James Currier,NFX,General Partner,Sweet spot: $2.5M,Range: $500K - $4.0M,James,Currier,james@nfx.com,valid
4,Peter Thiel,Founders Fund,Managing Partner,Sweet spot: $10.0M,Range: $1M - $20.0M,Peter,Thiel,peter@foundersfund.com,accept_all