CONTENTS:

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [14]:
!sudo /bin/bash -c "(source /venv/bin/activate; pip install --quiet jupyterlab-vim)"
!sudo /bin/bash -c "source /venv/bin/activate && pip install google-api-python-client"

!jupyter labextension enable

Collecting google-api-python-client
  Downloading google_api_python_client-2.159.0-py2.py3-none-any.whl.metadata (6.7 kB)
Collecting httplib2<1.dev0,>=0.19.0 (from google-api-python-client)
  Downloading httplib2-0.22.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0 in /venv/lib/python3.12/site-packages (from google-api-python-client) (2.36.0)
Collecting google-auth-httplib2<1.0.0,>=0.2.0 (from google-api-python-client)
  Downloading google_auth_httplib2-0.2.0-py2.py3-none-any.whl.metadata (2.2 kB)
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5 (from google-api-python-client)
  Downloading google_api_core-2.24.0-py3-none-any.whl.metadata (3.0 kB)
Collecting uritemplate<5,>=3.0.1 (from google-api-python-client)
  Downloading uritemplate-4.1.1-py2.py3-none-any.whl.metadata (2.9 kB)
Collecting googleapis-common-protos<2.0.dev0,>=1.56.2 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client)
  Downloading googleapis_common_protos-1.66.0-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.19.5 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client)
  Downloading protobuf-5.29.3-cp38-abi3-manylinux2014_x86_64.whl.metadata (592 bytes)
Collecting proto-plus<2.0.0dev,>=1.22.3 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client)
  Downloading proto_plus-1.26.0-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in /venv/lib/python3.12/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2.32.3)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /venv/lib/python3.12/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client) (5.5.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /venv/lib/python3.12/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /venv/lib/python3.12/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client) (4.2)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /venv/lib/python3.12/site-packages (from httplib2<1.dev0,>=0.19.0->google-api-python-client) (3.2.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /venv/lib/python3.12/site-packages (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client) (0.6.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /venv/lib/python3.12/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /venv/lib/python3.12/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /venv/lib/python3.12/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /venv/lib/python3.12/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2024.8.30)
Downloading google_api_python_client-2.159.0-py2.py3-none-any.whl (12.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 95.4 MB/s eta 0:00:00:00:010:01
Downloading google_api_core-2.24.0-py3-none-any.whl (158 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.6/158.6 kB 21.9 MB/s eta 0:00:00
Downloading google_auth_httplib2-0.2.0-py2.py3-none-any.whl (9.3 kB)
Downloading httplib2-0.22.0-py3-none-any.whl (96 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.9/96.9 kB 12.3 MB/s eta 0:00:00
Downloading uritemplate-4.1.1-py2.py3-none-any.whl (10 kB)
Downloading googleapis_common_protos-1.66.0-py2.py3-none-any.whl (221 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 221.7/221.7 kB 22.4 MB/s eta 0:00:00
Downloading proto_plus-1.26.0-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 4.9 MB/s eta 0:00:00
Downloading protobuf-5.29.3-cp38-abi3-manylinux2014_x86_64.whl (319 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.7/319.7 kB 25.3 MB/s eta 0:00:00
Installing collected packages: uritemplate, protobuf, httplib2, proto-plus, googleapis-common-protos, google-auth-httplib2, google-api-core, google-api-python-client
Successfully installed google-api-core-2.24.0 google-api-python-client-2.159.0 google-auth-httplib2-0.2.0 googleapis-common-protos-1.66.0 httplib2-0.22.0 proto-plus-1.26.0 protobuf-5.29.3 uritemplate-4.1.1

In [ ]:
import logging

import pandas as pd

# /venv/lib/python3.12/site-packages/gspread_pandas/spread.py:401: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)` .replace("", np.nan)
pd.set_option("future.no_silent_downcasting", True)

import helpers.hdbg as hdbg
import helpers.henv as henv
import helpers.hprint as hprint

# hcache.get_global_cache_info()
# hcache.clear_global_cache("all")

In [3]:
hdbg.init_logger(verbosity=logging.INFO)

_LOG = logging.getLogger(__name__)

_LOG.info("%s", henv.get_system_signature()[0])

hprint.config_notebook()

WARNING: Running in Jupyter
INFO  > cmd='/venv/lib/python3.12/site-packages/ipykernel_launcher.py -f /home/.local/share/jupyter/runtime/kernel-2d8c1236-7801-461f-85f8-9d3549253f24.json'
INFO  # Git
  branch_name='CmampTasl11283_Scrape_airtable_into_a_CSV'
  hash='cd2804ce7'
  # Last commits:
    * cd2804ce7 CK Bot   Update helpers repo                                               (    3 days ago) Sat Jan 25 01:37:18 2025  (HEAD -> CmampTasl11283_Scrape_airtable_into_a_CSV, origin/master, origin/HEAD, master)
    * 7ed995f51 Heanh Sok CmampTask10332_Automate_sprint_management_in_GitHub_Projects (#11235) (    3 days ago) Fri Jan 24 15:50:51 2025
    * b357ec0d4 Nina Lee CmTask11259_Perform_demand_EDA_spp_hourly_load_2 (#11272)         (    3 days ago) Fri Jan 24 12:13:49 2025
# Machine info
  system=Linux
  node name=4860048e33b5
  release=5.15.0-1075-aws
  version=#82~20.04.1-Ubuntu SMP Thu Dec 19 05:24:09 UTC 2024
  machine=x86_64
  processor=x86_64
  cpu count=8
  cpu freq=scpufreq(current=2499.998, min=0.0, max=0.0)
  memory=svmem(total=33280225280, available=19299975168, percent=42.0, used=13499252736, free=267993088, active=9270898688, inactive=16869752832, buffers=3726413824, cached=15786565632, shared=3289088, slab=6361153536)
  disk usage=sdiskusage(total=249734021120, used=132982177792, free=116735066112, percent=53.3)
# Packages
  python: 3.12.3
  cvxopt: 1.3.2
  cvxpy: 1.5.3
  gluonnlp: ?
  gluonts: ?
  joblib: 1.4.2
  mxnet: ?
  numpy: 2.1.3
  pandas: 2.2.3
  pyarrow: 18.0.0
  scipy: 1.14.1
  seaborn: 0.13.2
  sklearn: 1.5.2
  statsmodels: 0.14.4

In [15]:
from ck_marketing.process_automation.workflows import GoogleSheetsHelper as GSH

In [16]:
gsheet_helper = GSH()

In [33]:
df_air = gsheet_helper.read_sheet("10t1YxmCTu3Kl8q3QsT-CqWWuXgg28bxtrpkNUnHp8Zo")

In [34]:
df_air.head()

                       Family Office            Name                              Email           City State                               Website Error_row
0  Fleming Family & Partners Limited   Ahmet Feridun           ahmet.feridun@ffandp.com         London     –                                     –
1                     Stamos Capital    Ron Marryott        rmarryott@stamoscapital.com              –    CA  https://www.stamoscapital.com/about/
2                     TAG Associates  John Pantowich            jpantowich@tagassoc.com       New York    NY                                     –
3               HOLBEIN PARTNERS LLP   ANDERE RODGER  andere.rodger@holbeinpartners.com         London     –       http://www.holbeinpartners.com/
4                     ICONIQ Capital  Vid Mahansaria              vid@iconiqcapital.com  San Francisco    CA         http://www.iconiqcapital.com/

In [35]:
len(df_air)

6253

In [36]:
df_air[10:15]

                Family Office                 Name                              Email                      City    State                        Website                    Error_row
10            Perspecta Trust      STEPHEN J. TALL           stall@perspectatrust.com                   Hampton       NH    https://perspectatrust.com/
11            Perspecta Trust                 Open                    STEPHEN J. TALL  stall@perspectatrust.com  Hampton                             NH  https://perspectatrust.com/
12  Habif Arogeti & Wynne LLP          Edward Deck                 ed.deck@hawcpa.com                   Atlanta       GA                info@hawcpa.com
13    Piedmont Partners Group        Stephen Leist  shleist@piedmontpartnersgroup.com                  Piedmont       CA  www.piedmontpartnersgroup.com
14  Baldwin Family Office LLC  Susan Berry Kohlhas             skohlhas@baldwinim.com         West Conshohocken       PA                              –

In [41]:
def fix_shifted_rows(df):
    for index, row in df.iterrows():
        if row["Name"] == "Open":
            df.loc[index, "Name"] = row["Email"]
            df.loc[index, "Email"] = row["City"]
            df.loc[index, "City"] = row["State"]
            df.loc[index, "State"] = row["Website"]
            df.loc[index, "Website"] = row["Error_row"]
            df.loc[index, "Error_row"] = ""
    return df

In [42]:
df_air_cleaned = fix_shifted_rows(df_air)

In [43]:
len(df_air_cleaned)

6253

In [44]:
df_air_cleaned[10:15]

                Family Office                 Name                              Email               City State                        Website Error_row
10            Perspecta Trust      STEPHEN J. TALL           stall@perspectatrust.com            Hampton    NH    https://perspectatrust.com/
11            Perspecta Trust      STEPHEN J. TALL           stall@perspectatrust.com            Hampton    NH    https://perspectatrust.com/      None
12  Habif Arogeti & Wynne LLP          Edward Deck                 ed.deck@hawcpa.com            Atlanta    GA                info@hawcpa.com
13    Piedmont Partners Group        Stephen Leist  shleist@piedmontpartnersgroup.com           Piedmont    CA  www.piedmontpartnersgroup.com
14  Baldwin Family Office LLC  Susan Berry Kohlhas             skohlhas@baldwinim.com  West Conshohocken    PA                              –

In [47]:
gsheet_helper.write_results(
    "10t1YxmCTu3Kl8q3QsT-CqWWuXgg28bxtrpkNUnHp8Zo", df_air_cleaned, "cleaned_data"
)

INFO  Results saved in the new tab: cleaned_data