# Description

This script reads data, extracts mails of people using HunterIO and Dropcontact and writes it back to google sheet

In [20]:
!sudo /bin/bash -c "(source /venv/bin/activate; pip install --upgrade google-api-python-client)"

In [3]:
import logging

import ck_marketing.hunterio.hunter_api as cmhuhuap
import helpers.hdbg as hdbg
import helpers.henv as henv
import helpers.hprint as hprint
from ck_marketing.hunterio.hunter_api import GoogleSheetsHelper

In [4]:
# Configure logger.
hdbg.init_logger(verbosity=logging.INFO)
_LOG = logging.getLogger(__name__)

# Print system signature.
_LOG.info("%s", henv.get_system_signature()[0])

# Configure the notebook style.
hprint.config_notebook()

DEBUG:helpers.hsystem:> (cd . && cd "$(git rev-parse --show-toplevel)/.." && (git rev-parse --is-inside-work-tree | grep -q true)) 2>&1
DEBUG:helpers.hsystem:> (git rev-parse --show-toplevel) 2>&1
DEBUG:helpers.hsystem:> (git branch --show-current) 2>&1
DEBUG:helpers.hsystem:> (git rev-parse --short HEAD) 2>&1
DEBUG:helpers.hsystem:> (git log --date=local --oneline --graph --date-order --decorate --pretty=format:'%h %<(8)%aN%  %<(65)%s (%>(14)%ar) %ad %<(10)%d' -3) 2>&1

WARNING: Logger already initialized: skipping

INFO:__main__:# Git
  branch_name='CmTask11085_Money_20_extract_email'
  hash='4eb17323e'
  # Last commits:
    * 4eb17323e Shayan   integrate GitHub app approach (#11053)                            (    3 days ago) Wed Dec 18 17:11:23 2024  (HEAD -> CmTask11085_Money_20_extract_email, origin/master, origin/HEAD, master)
    * 9220c3158 Nina Lee CmTask10968_C11a.config3_shadow_trading_DAG_reconciliation_fails (#11014) (    4 days ago) Tue Dec 17 22:21:43 2024
    * 2d9a645b1 Heanh Sok CmampTask10224_Make_infra_dir_releasable_3 (#10972)               (    4 days ago) Tue Dec 17 21:08:14 2024
# Machine info
  system=Linux
  node name=a4af410f3554
  release=5.15.0-1072-aws
  version=#78~20.04.1-Ubuntu SMP Wed Oct 9 15:30:47 UTC 2024
  machine=x86_64
  processor=x86_64
  cpu count=8
  cpu freq=scpufreq(current=2499.998, min=0.0, max=0.0)
  memory=svmem(total=33280225280, available=25236455424, percent=24.2, used=7555588096, free=3470036992, active=7284064256, inactive=14162096128, buffers=3085856768, cached=19168743424, shared=3784704, slab=7967420416)
  disk usage=sdiskusage(total=249734021120, used=128220209152, free=121497034752, percent=51.3)
# Packages
  python: 3.12.3
  cvxopt: 1.3.2
  cvxpy: 1.5.3
  gluonnlp: ?
  gluonts: ?
  joblib: 1.4.2
  mxnet: ?
  numpy: 2.1.3
  pandas: 2.2.3
  pyarrow: 18.0.0
  scipy: 1.14.1
  seaborn: 0.13.2
  sklearn: 1.5.2
  statsmodels: 0.14.4

In [6]:
# Google Drive Setup.
google_creds_path = "service.json"
google_sheet_helper = GoogleSheetsHelper(google_creds_path)

In [8]:
file_id = "1--ERHzSPVWgfFqjXQwGhFv4siH-RJIwoNr6iZC1pHJ8"
sheet = google_sheet_helper.google_account.open_by_key(file_id)
money_df = google_sheet_helper.read_sheet(file_id)

INFO:root:Opened spreadsheet with ID: 1--ERHzSPVWgfFqjXQwGhFv4siH-RJIwoNr6iZC1pHJ8
INFO:root:Selected worksheet: Sheet1

In [9]:
len(money_df)

500

In [11]:
money_df.tail()

             fullname                 companyName                         jobTitle                    location Notes Skip Buyer/Software Insurance Bank Lending Cloud Partner ISV VC? Invest
495     Deanna Blaise  Valley Strong Credit Union     SVP Member Business Services  Bakersfield, United States                                        ✔
496      Jonas Jacobi                   ValidMind                 CEO & Co-founder    Palo Alto, United States
497   Charles Fischer                   ValidMind            Chief Revenue Officer                        None
498  Michael Roenning                   ValidMind  Director, Solution Architecture                        None
499        Greg Rable                    ValidiFI                              CEO                        None

In [13]:
money_df[["firstName", "lastName"]] = money_df["fullname"].str.split(
    " ", n=1, expand=True
)

In [15]:
title_clean = "cleaned_profiles"
cleaned_profiles_tab = sheet.add_worksheet(
    title=title_clean, rows="100", cols="20"
)
google_sheet_helper.write_results(file_id, money_df, title_clean)

INFO:ck_marketing.hunterio.hunter_api:Email extraction completed. Results saved in the new tab: cleaned_profiles

In [16]:
money_df.tail()

             fullname                 companyName                         jobTitle                    location Notes Skip Buyer/Software Insurance Bank Lending Cloud Partner ISV VC? Invest firstName  lastName
495     Deanna Blaise  Valley Strong Credit Union     SVP Member Business Services  Bakersfield, United States                                        ✔                                         Deanna    Blaise
496      Jonas Jacobi                   ValidMind                 CEO & Co-founder    Palo Alto, United States                                                                                   Jonas    Jacobi
497   Charles Fischer                   ValidMind            Chief Revenue Officer                        None                                                                                 Charles   Fischer
498  Michael Roenning                   ValidMind  Director, Solution Architecture                        None                                                                                 Michael  Roenning
499        Greg Rable                    ValidiFI                              CEO                        None                                                                                    Greg     Rable

In [19]:
merged_df = cmhuhuap.hunter_drop_emails(
    "firstName",
    "lastName",
    "companyName",
    title_clean,
    hunter_api_key,
    google_creds_path,
    file_id,
    dropcontact_api_key,
)

INFO:ck_marketing.hunterio.hunter_api:Starting process to read records and find emails
INFO:root:Opened spreadsheet with ID: 1--ERHzSPVWgfFqjXQwGhFv4siH-RJIwoNr6iZC1pHJ8
INFO:root:Selected worksheet: cleaned_profiles
INFO:ck_marketing.hunterio.hunter_api:Finding bulk emails using company name
WARNING:ck_marketing.hunterio.hunter_api:Error fetching email for Nicole Zimmermann at ZELOCIN & Partners: 502 Server Error: Bad Gateway for url: https://api.hunter.io/v2/email-finder?company=ZELOCIN%20&%20Partners&first_name=Nicole&last_name=Zimmermann&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
INFO:ck_marketing.hunterio.hunter_api:Writing results to Google Sheets
INFO:ck_marketing.hunterio.hunter_api:Email extraction completed. Results saved in the new tab: hunter_results
INFO:ck_marketing.hunterio.hunter_api:Total records processed: 500
INFO:ck_marketing.hunterio.hunter_api:Emails found: 295
INFO:ck_marketing.hunterio.hunter_api:Emails not found: 205
INFO:ck_marketing.hunterio.hunter_api:Number of unique companies: 226
INFO:ck_marketing.hunterio.hunter_api:Percentage of emails found: 59.00%
INFO:ck_marketing.hunterio.hunter_api:Companies by number of records:
INFO:ck_marketing.hunterio.hunter_api:companyName
Visa                                                                                    52
Worldpay                                                                                32
Wells Fargo                                                                             26
Walmart                                                                                  9
WEX                                                                                      9
Wise                                                                                     9
Zelis                                                                                    8
Xsolla                                                                                   7
Zip                                                                                      7
Wipro Limited                                                                            6
Volt                                                                                     5
VGS                                                                                      5
William Blair                                                                            4
Wyzia Financial Inc.                                                                     4
Yuno                                                                                     4
Zip Co                                                                                   4
ZoomInfo Technologies LLC                                                                4
Wolf & Company PC                                                                        4
Wachsman PR                                                                              4
Western Alliance Bank                                                                    4
Vestigo Ventures                                                                         4
VIMworld Inc                                                                             4
Vanguard                                                                                 4
WEX, Inc.                                                                                4
Voltage                                                                                  3
Wachsman                                                                                 3
White & Case LLP                                                                         3
Veritran                                                                                 3
Xoriant                                                                                  3
Zafin                                                                                    3
ZenBusiness                                                                              3
Worth AI                                                                                 3
WTM USA INTERNATIONAL PAYMENTS                                                           3
Xero                                                                                     3
Wells Fargo Bank                                                                         3
ValidMind                                                                                3
Veriff                                                                                   3
Viamericas Corporation                                                                   3
velera                                                                                   3
Westlake Financial                                                                       2
Welsh Government                                                                         2
WebBank                                                                                  2
Walkabout Ventures                                                                       2
VoPay International Inc.                                                                 2
Waller Helms Advisors                                                                    2
Vizum                                                                                    2
WebID Solutions GmbH                                                                     2
Walnut Insurance Inc.                                                                    2
Wally Tech Panama                                                                        2
Warburg Pincus                                                                           2
WINR Data                                                                                2
VENTI GLOBAL INC.                                                                        2
Vendara Payments                                                                         2
Venture Solutions                                                                        2
ValueLabs                                                                                2
Valley Strong Credit Union                                                               2
Vechain Foundation                                                                       2
Vansary                                                                                  2
Viola Ventures                                                                           2
Venteur                                                                                  2
Verifone, Inc.                                                                           2
Vested                                                                                   2
Vic.ai                                                                                   2
Veryfi                                                                                   2
Vista Equity Partners                                                                    2
Vitruvian Partners                                                                       2
Wells Fargo Strategic Capital                                                            2
Wysh                                                                                     2
Xflow                                                                                    2
Xplor Technologies, LLC                                                                  2
Yardi Systems, Inc.                                                                      2
Zuora                                                                                    2
Zapp                                                                                     2
Zil Money                                                                                2
Zumigo                                                                                   2
Zero Hash LLC                                                                            2
YouPay                                                                                   2
ZBD                                                                                      2
Zolve                                                                                    2
wirewand limited                                                                         2
Wolfpack Financial Inc                                                                   2
Volition Capital                                                                         2
Verified                                                                                 2
WorkWave                                                                                 2
YouLend                                                                                  1
Yirael Technology LLC                                                                    1
Yuhu                                                                                     1
Yrefy, LLC                                                                               1
Yummit Finance LLC                                                                       1
Yoda Consulting                                                                          1
ZEBEDEE LLC                                                                              1
ZELOCIN™ and Partners                                                                    1
ZULU                                                                                     1
Zulie venture Inc                                                                        1
Zimperium                                                                                1
ZEPZ (World remit and Sendwave)                                                          1
Zentact, Inc.                                                                            1
ZELOCIN & Partners                                                                       1
Whatnot                                                                                  1
Whish Money USA, LLC                                                                     1
Wilen Group                                                                              1
Wilh. Werhahn KG                                                                         1
WILLPORT Holdings,Inc                                                                    1
William Mills Agency                                                                     1
Winston & Strawn LLP                                                                     1
Wink                                                                                     1
Wipro Ltd                                                                                1
Wipro                                                                                    1
WinWinX, Inc                                                                             1
WiPay LLC                                                                                1
Wise (formerly Transferwise)                                                             1
Wise Platform at Wise (formerly Transferwise)                                            1
WireBarley America Inc.                                                                  1
WireBarley                                                                               1
World Innovation Lab (WiL)                                                               1
Workato                                                                                  1
Workforce Innovation, Trust and Influence (f.k.a. Women in Technology International)     1
Wolfe, LLC                                                                               1
WiseWallet                                                                               1
Withum+                                                                                  1
Wolters Kluwer                                                                           1
Xero, Inc.                                                                               1
X Payments LLC                                                                           1
X Amazon and Capital Group                                                               1
Xceptor                                                                                  1
WyreWorks                                                                                1
Wrnt.Co                                                                                  1
Worldpay, LLC                                                                            1
Worldpay for Platforms                                                                   1
Worldline                                                                                1
Yellow Card                                                                              1
Yellow Brick Road Payments                                                               1
Yext                                                                                     1
Yape                                                                                     1
Yardi Systems                                                                            1
Yahoo Finance                                                                            1
Yale Daily News                                                                          1
Yamaha Motor Ventures                                                                    1
XU Magazine                                                                              1
X4 Technology                                                                            1
Yaspa                                                                                    1
Yell Payment                                                                             1
your.fintechgf                                                                           1
Zup IT Innovation                                                                        1
Zolve Innovations Inc.                                                                   1
Zumma                                                                                    1
Zensar Technologies - Dallas                                                             1
Warren Investimentos                                                                     1
Warrant                                                                                  1
Waterhouse-Kern Associates                                                               1
WDS World Digital Solutions                                                              1
Wealthsimple                                                                             1
Warren Investimentos | Pinheiros - SP                                                    1
West Monroe                                                                              1
Wells Fargo Securities LLC                                                               1
Wellth360                                                                                1
WestBridge Capital                                                                       1
West Monroe Partners                                                                     1
Wenia Ltd                                                                                1
Western Union                                                                            1
Westerra Credit Union                                                                    1
WHALET Pte Ltd                                                                           1
Vixel                                                                                    1
Vixio                                                                                    1
VN                                                                                       1
VN.com                                                                                   1
Volascope Labs                                                                           1
Volante Tech                                                                             1
Vonage                                                                                   1
Volt.io                                                                                  1
VT Volio Digital                                                                         1
Vor Capital Llp                                                                          1
Voyantis                                                                                 1
Walmart Labs                                                                             1
Walmart Marketplace                                                                      1
WARC                                                                                     1
Wallbit                                                                                  1
Walker Sands                                                                             1
Walmart Ecommerce                                                                        1
Walmart Inc.,                                                                            1
Walmart at Walmart                                                                       1
Wellfit Technologies, Inc.                                                               1
Wellesley Hills Financial, LLC                                                           1
Wellfit Technologies, Inc                                                                1
Webster Bank-interLINK Division                                                          1
Webull                                                                                   1
Web3 Marketing Inc                                                                       1
Web Summit                                                                               1
Vincent                                                                                  1
Viking Global                                                                            1
ViewTrade                                                                                1
VISA Global Headquarters                                                                 1
Visa, Inc.                                                                               1
Vista Credit Partners                                                                    1
Verinite Technologies Pvt Ltd                                                            1
VerisFi Capital                                                                          1
Vertex Inc.                                                                              1
Versal.money                                                                             1
Vervent                                                                                  1
Viewpoint Ventures                                                                       1
Vibes                                                                                    1
VESTECH                                                                                  1
Virtual Alarm Dealer                                                                     1
Virtual Golf Rentals                                                                     1
VION Investments                                                                         1
VIPRev,LLC                                                                               1

Starting query batch 0.
Batch 0: Query ID: ynldenxysrzzken.

Processing batches:  20%|#########                                    | 1/5 [01:34<06:17, 94.37s/it]

Batch 0: Query finished. Credits left: 5726.
Batch 0 completed in 94.37 seconds.
Starting query batch 1.
Batch 1: Query ID: cmotmtoejefbifq.

Processing batches:  40%|##################                           | 2/5 [02:58<04:24, 88.20s/it]

Batch 1: Query finished. Credits left: 5676.
Batch 1 completed in 83.88 seconds.
Starting query batch 2.
Batch 2: Query ID: nnuzvndaursepdm.

Processing batches:  60%|###########################                  | 3/5 [04:22<02:52, 86.32s/it]

Batch 2: Query finished. Credits left: 5626.
Batch 2 completed in 84.09 seconds.
Starting query batch 3.
Batch 3: Query ID: okffjqbgyqjzcjt.

Processing batches:  80%|####################################         | 4/5 [05:25<01:17, 77.23s/it]

Batch 3: Query finished. Credits left: 5576.
Batch 3 completed in 63.29 seconds.
Starting query batch 4.
Batch 4: Query ID: fztmdoguuqclaxd.

Processing batches: 100%|#############################################| 5/5 [05:56<00:00, 71.32s/it]
INFO:ck_marketing.hunterio.hunter_api:Number of emails found : 132
INFO:ck_marketing.hunterio.hunter_api:Number of profile emails hunter could not find 205:

Batch 4: Query finished. Credits left: 5571.
Batch 4 completed in 30.97 seconds.
Total processing time: 356.60 seconds.

INFO:ck_marketing.hunterio.hunter_api:Email extraction completed. Results saved in the new tab: hunter_drop_emails
INFO:ck_marketing.hunterio.hunter_api:Email extraction completed. Results saved in the new tab: all_emails