In [23]:
import logging
import os

import ck_marketing.hunterio.hunter_api as cmhuhuap
import ck_marketing.linkedin.linkedin_utils as cmliprfi
import helpers.hdbg as hdbg
import helpers.henv as henv
import helpers.hprint as hprint
from ck_marketing.hunterio.hunter_api import GoogleSheetsHelper, HunterIO
from ck_marketing.linkedin.phantombuster_api import Phantom

In [36]:
# Configure logger.
hdbg.init_logger(verbosity=logging.INFO)
_LOG = logging.getLogger(__name__)

# Print system signature.
_LOG.info("%s", henv.get_system_signature()[0])

# Configure the notebook style.
hprint.config_notebook()

DEBUG:helpers.hsystem:> (cd . && cd "$(git rev-parse --show-toplevel)/.." && (git rev-parse --is-inside-work-tree | grep -q true)) 2>&1
DEBUG:helpers.hsystem:> (git rev-parse --show-toplevel) 2>&1
DEBUG:helpers.hsystem:> (git branch --show-current) 2>&1
DEBUG:helpers.hsystem:> (git rev-parse --short HEAD) 2>&1
DEBUG:helpers.hsystem:> (git log --date=local --oneline --graph --date-order --decorate --pretty=format:'%h %<(8)%aN%  %<(65)%s (%>(14)%ar) %ad %<(10)%d' -3) 2>&1

WARNING: Logger already initialized: skipping

INFO:__main__:# Git
  branch_name='CmTask10992__Build_pipeline_for_email_validation'
  hash='2d8544eb0'
  # Last commits:
    * 2d8544eb0 Shayan   AWS CloudWatch Synthetics Canaries documented (#10930)            (    9 days ago) Tue Dec 3 16:21:18 2024  (HEAD -> CmTask10992__Build_pipeline_for_email_validation, origin/master, origin/HEAD, master)
    * 6baf44a3c Nina Lee CmTask10927 Fix cmd in publish_master_trading_notebook            (    9 days ago) Tue Dec 3 14:41:15 2024
    * f25cb3799 Nina Lee CMTask 10922 Fix build_run_notebook_cmd() call (#10924)           (    9 days ago) Tue Dec 3 13:58:07 2024
# Machine info
  system=Linux
  node name=5b818430e535
  release=5.15.0-1072-aws
  version=#78~20.04.1-Ubuntu SMP Wed Oct 9 15:30:47 UTC 2024
  machine=x86_64
  processor=x86_64
  cpu count=8
  cpu freq=scpufreq(current=2499.998, min=0.0, max=0.0)
  memory=svmem(total=33280225280, available=24316379136, percent=26.9, used=8473686016, free=4250132480, active=3888664576, inactive=7055147008, buffers=967696384, cached=19588710400, shared=2662400, slab=17729880064)
  disk usage=sdiskusage(total=249734021120, used=145880068096, free=103837175808, percent=58.4)
# Packages
  python: 3.12.3
  cvxopt: 1.3.2
  cvxpy: 1.5.3
  gluonnlp: ?
  gluonts: ?
  joblib: 1.4.2
  mxnet: ?
  numpy: 2.1.3
  pandas: 2.2.3
  pyarrow: 18.0.0
  scipy: 1.14.1
  seaborn: 0.13.2
  sklearn: 1.5.2
  statsmodels: 0.14.4

# Clean Profiles

In [37]:
hunter_api_key = os.getenv("Hunter_API_KEY")

In [30]:
# Google Drive Setup.
google_creds_path = "service.json"
google_sheet_helper = GoogleSheetsHelper(google_creds_path)
file_id = "1UOov0ZmZoCVBIUg825k9LgT8m6p43aW91aR2WmJNDcg"

In [31]:
df = google_sheet_helper.read_sheet(file_id)

INFO:root:Opened spreadsheet with ID: 1UOov0ZmZoCVBIUg825k9LgT8m6p43aW91aR2WmJNDcg
INFO:root:Selected worksheet: Sheet1

In [32]:
df.head()

,Person - Name,Person - Email - Work,Person - Email - Home,Person - Email - Other,Person - Phone - Work,Person - Phone - Home,Person - Phone - Mobile,Person - Phone - Other
0,A Gadala,a.gadala@gbh.com.do,,,,,,
1,A Guzman,a.guzman@gbh.com.do,,,,,,
2,A.M. Saad,ams@btbmed.com,,,,,,
3,Aadeel Akhtar,aakhtar@psyonic.co,,,,,,
4,Aage Lauridsen,aage.lauridsen@enterahealth.com,,,(515) 289-7652,,,

# Verify Email

In [33]:
hunter_instance = HunterIO(hunter_api_key)
verified_df = hunter_instance.verify_emails(df, "Person - Email - Work")

WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email abel.clark@cision.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=abel.clark@cision.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	Adam@l3blockchaim.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09Adam@l3blockchaim.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email adam.foroughi@applovin.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=adam.foroughi@applovin.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	alberto.sanchez@citynational.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09alberto.sanchez@citynational.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email aleksander@feathr.co: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=aleksander@feathr.co&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email alex@branch.io: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=alex@branch.io&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	oleksandr.movchan@pm.bet: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09oleksandr.movchan@pm.bet&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 393316615726: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=393316615726&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	annieyu@box.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09annieyu@box.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	Office@berlainteriors.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09Office@berlainteriors.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	bgiordani@vestmark.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09bgiordani@vestmark.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email bob@infolinks.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=bob@infolinks.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email bozena.morenc@aarki.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=bozena.morenc@aarki.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email bradley@ripple.com, bg@ripple.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=bradley@ripple.com,%20bg@ripple.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	blynn@digits.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09blynn@digits.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	brittanytruex@waypointbuilding.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09brittanytruex@waypointbuilding.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email bryan.gernert@resonate.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=bryan.gernert@resonate.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email corey@jungroup.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=corey@jungroup.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	dan@deepscribe.ai: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09dan@deepscribe.ai&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email dan@advertise.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=dan@advertise.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email dcarhart@branch.io: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=dcarhart@branch.io&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	dreitz@hightoweradvisors.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09dreitz@hightoweradvisors.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email dennis.becker@mobivity.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=dennis.becker@mobivity.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email djohnson@tatango.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=djohnson@tatango.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email diana.biggs.hsbc.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=diana.biggs.hsbc.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	dp1@mainTstar.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09dp1@mainTstar.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email ami.shah@f2fhealth: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=ami.shah@f2fhealth&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	erik@thehizzle.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09erik@thehizzle.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	fchang@psionline.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09fchang@psionline.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	gdiop@jogiwork.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09gdiop@jogiwork.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email grogol@demandbase.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=grogol@demandbase.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email gherebia@redmas.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=gherebia@redmas.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email gincitti@sitetracker.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=gincitti@sitetracker.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email gladys@ubermedia.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=gladys@ubermedia.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	gbarbee@lyft.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09gbarbee@lyft.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email greg.morton@ensighten.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=greg.morton@ensighten.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	gunjit@electricsheep.company: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09gunjit@electricsheep.company&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email htang@spokeo.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=htang@spokeo.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	hennie@crackerjackhire.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09hennie@crackerjackhire.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	hq.qiu@cheddar.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09hq.qiu@cheddar.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email ian.bennett@alefedge.com, ian.bennett@alefedge.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=ian.bennett@alefedge.com,%20ian.bennett@alefedge.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email ian.woolley@ensighten.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=ian.woolley@ensighten.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email https://www.linkedin.com/in/ilanagamza/: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=https://www.linkedin.com/in/ilanagamza/&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	Imran.khan@hanu.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09Imran.khan@hanu.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	jack@high-five.capital: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09jack@high-five.capital&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	Jacob@wafiapps.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09Jacob@wafiapps.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email rhodri.james@northrow.comadrian.molenaar@northrow.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=rhodri.james@northrow.comadrian.molenaar@northrow.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	jaz@ziggletech.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09jaz@ziggletech.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	jlandes@cobank.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09jlandes@cobank.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	jeff@blendedharvest.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09jeff@blendedharvest.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email jeremy.bondy@vungle.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=jeremy.bondy@vungle.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	jessica.torres@mrinetwork.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09jessica.torres@mrinetwork.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email jim@adtheorent.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=jim@adtheorent.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	joe.tawfik@kineticcs.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09joe.tawfik@kineticcs.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email linkedin.com/in/john-crisostomo-58b8743: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=linkedin.com/in/john-crisostomo-58b8743&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email john@chartbeat.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=john@chartbeat.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	johnson.chua@prudential.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09johnson.chua@prudential.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	jjarrett@guidehouse.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09jjarrett@guidehouse.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	petitarian@petitarian.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09petitarian@petitarian.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email kswift@@silver-peak.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=kswift@@silver-peak.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email kayt.leonard@psi-cro.com, Kayt.Leonard@psi-cro.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=kayt.leonard@psi-cro.com,%20Kayt.Leonard@psi-cro.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	kei.kinoshita@kinship.co: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09kei.kinoshita@kinship.co&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	kemal.pehlivan@edu-zone.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09kemal.pehlivan@edu-zone.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	kenneth.cruz@shift4shop.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09kenneth.cruz@shift4shop.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	kevin.payne@objectivemanager.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09kevin.payne@objectivemanager.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	kborg@predtictive-grid-analytics.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09kborg@predtictive-grid-analytics.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email Lcuddy@envasetechnologies.com, lcuddy@nascent.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=Lcuddy@envasetechnologies.com,%20lcuddy@nascent.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	LTURNER@POWERLEVELTECHNOLOGY.COM: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09LTURNER@POWERLEVELTECHNOLOGY.COM&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email laurent.corneille@inspirationaldg.com Phone: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=laurent.corneille@inspirationaldg.com%20Phone&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	slack@tehama.io: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09slack@tehama.io&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email +34 658 917 899: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=+34%20658%20917%20899&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email lisa.cleary@swrve.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=lisa.cleary@swrve.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	lw@delacourconsulting.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09lw@delacourconsulting.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	maddie@optinstrategies.org: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09maddie@optinstrategies.org&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email manish.narula@treasuredata.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=manish.narula@treasuredata.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	mnelson@biopm.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09mnelson@biopm.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email martin@coinmama.com, Asaph Schulman: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=martin@coinmama.com,%20Asaph%20Schulman&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email marty.greenlow@ensighten.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=marty.greenlow@ensighten.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16
WARNING:ck_marketing.hunterio.hunter_apii:Error verifying email 	massimo.young@insightinvestment.com: 400 Client Error: Bad Request for url: https://api.hunter.io/v2/email-verifier?email=%09massimo.young@insightinvestment.com&api_key=89afbf8e860cc8a9af6d8c66d0bfd0844815af16

In [35]:
sheet = google_sheet_helper.google_account.open_by_key(file_id)
cleaned_profiles_tab = sheet.add_worksheet(
    title="hunter_verification", rows="100", cols="20"
)
google_sheet_helper.write_results(file_id, verified_df, "hunter_verification")

INFO:ck_marketing.hunterio.hunter_apii:Email extraction completed. Results saved in the new tab: hunter_verification

In [34]:
verified_df.head()

,Person - Name,Person - Email - Work,Person - Email - Home,Person - Email - Other,Person - Phone - Work,Person - Phone - Home,Person - Phone - Mobile,Person - Phone - Other,hunter_verification
0,A Gadala,a.gadala@gbh.com.do,,,,,,,valid
1,A Guzman,a.guzman@gbh.com.do,,,,,,,valid
2,A.M. Saad,ams@btbmed.com,,,,,,,invalid
3,Aadeel Akhtar,aakhtar@psyonic.co,,,,,,,valid
4,Aage Lauridsen,aage.lauridsen@enterahealth.com,,,(515) 289-7652,,,,valid